### ISSUE TITLE
Missing page information in facebook channel

### ISSUE THREAD

**Issue by yochail** [microsoft/botbuilder-tools#1288] opened 2019-09-12 17:07 UTC
## Tool
Name: az CLI 
OS: win10

## Describe the bug
I'm trying to read programmatically the pages id+token connected to a bot.
I tried:
using azure management API with:
`https://management.azure.com/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.BotService/botServices/<name>/Channels/FacebookChannel?api-version=2018-07-12`
or the cli command: 

```bash
az bot facebook show --name <name> --resource-group <rg> --subscription <sub>
```
both are returning the channel data, but in some bot the pages object is null, and in some the token is empty.
what may be the problem? in some bots i was able to get both the pageID and the token

## To Reproduce
run az bot facebook show --name <name> --resource-group <rg> --subscription <sub>
## Expected behavior
returen all the page data

## Actual behavior
This is what i'm actualy getting:

```bash
{
  "etag": "W/\"e0c981d729ce21fd4476d53f7b08d7169/12/2019 4:59:31 PM\"",
  "id": "/subscriptions/dcad755b-cc47-45df-b590-b26b9fcbe58a/resourceGroups/DemoBots/providers/Microsoft.BotService/botServices/say2eat-test/channels/FacebookChannel",
  "kind": null,
  "location": "global",
  "name": "say2eat-test/FacebookChannel",
  "properties": {
    "channelName": "FacebookChannel",
    "etag": "W/\"e0c981d729ce21fd4476d53f7b08d7169/12/2019 4:59:31 PM\"",
    "location": "global",
    "properties": {
      "appId": "294907590851691",
      "appSecret": "",
      "callbackUrl": null,
      "isEnabled": true,
      "pages": [
        {
          "accessToken": "",
          "id": "330032927505775"
        }
      ],
      "verifyToken": "<tok>"
    },
    "provisioningState": "Succeeded"
  },
  "resourceGroup": "DemoBots",
  "sku": null,
  "tags": null,
  "type": "Microsoft.BotService/botServices/channels"
}
```

```bash
{
  "etag": "W/\"31101d5b69fdc7af4af5148470ad26cd9/12/2019 4:52:20 PM\"",
  "id": "/subscriptions/da729e14-dd4f-4a13-a150-5db54573bf22/resourceGroups/productionbots/providers/Microsoft.BotService/botServices/say2eat-bigdaddysanddukes/channels/FacebookChannel",
  "kind": null,
  "location": "global",
  "name": "say2eat-bigdaddysanddukes/FacebookChannel",
  "properties": {
    "channelName": "FacebookChannel",
    "etag": "W/\"31101d5b69fdc7af4af5148470ad26cd9/12/2019 4:52:20 PM\"",
    "location": "global",
    "properties": {
      "appId": null,
      "appSecret": "",
      "callbackUrl": null,
      "isEnabled": true,
      "pages": null,
      "verifyToken": "<tok>"
    },
    "provisioningState": "Succeeded"
  },
  "resourceGroup": "productionbots",
  "sku": null,
  "tags": null,
  "type": "Microsoft.BotService/botServices/channels"
}
```

[bug]

**Comment by stevengum** [comment] 2019-09-16 04:37
@swagatmishra2007 what's the expected behavior for this API?

**Comment by swagatmishra2007** [comment] 2019-09-18 23:45
The CLI (and rest api) wouldnt give show you secrets by default (This is true for most azure api's), so that you dont inverently expose your passwords/tokens on a command line.
To see secrets like "appSecret" , use the --with-secrets flag - 
az bot facebook --with-secrets

For the 2nd bot, where you are getting the pages as null, i am looking at it on the service side logs. i will update this thread once i find something

**Comment by yochail** [comment] 2019-09-19 08:00
@swagatmishra2007  I tried az bot facebook --with-secrets, which resulted in error.
is there a way to add the "with-secrets" flag to the management.azure.com API call?

**Comment by swagatmishra2007** [comment] 2019-09-19 22:18
@yochail  i am able to repro this on my bot and see its a service side issue. I will investigate and check in a fix and update this thread when the fix is deployed.
Thanks for reporting it

**Comment by stevengum** [comment] 2019-10-01 16:56
@swagatmishra2007 any updates on this issue?

**Comment by stevengum** [comment] 2019-10-02 17:08
@yochail the issue should be fixed as the bugfix went out in this week's deployment. Please test it again and let us know.

**Comment by cwhitten** [comment] 2019-10-14 18:23
Closing due to inactivity. @yochail we believe this issue is addressed. Please re-open if this issue is not fixed for you.

**Closed by cwhitten** 2019-10-14 18:23 UTC
Labels: Bot Services, customer-replied-to, customer-reported
