### ISSUE TITLE
DialogSchema: IfCondition says $copy is missing

### ISSUE THREAD

**Issue by tomlm** [Microsoft/botbuilder-tools#1099] opened 2019-04-27 01:07 UTC
```javascript
{
    "$schema": "../../app.schema",
    "$type": "Microsoft.AdaptiveDialog",
    "steps": [
        {
            "$type": "Microsoft.IfCondition",
            "condition": "user.name == null",
            "steps": [
                {
                    "$type": "Microsoft.TextInput",
                    "prompt": "Hello, I'm Zoidberg. What is your name?",
                    "property": "user.name"
                }
            ]
        },
        {
            "$type": "Microsoft.SendActivity",
            "activity": "Hello {user.name}, nice to talk to you!"
        }
    ]
}
```

**Comment by chrimc62** [comment] 2019-04-27 01:46
The issue is in the IfCondition schema which is fixed in botbuilder 4.next.

**Closed by chrimc62** 2019-04-27 01:46 UTC
