### ISSUE TITLE
Error when deleting luis version using msbot get as input

### ISSUE THREAD

**Issue by fbeauchemin** [Microsoft/botbuilder-tools#751] opened 2018-11-09 16:47 UTC
## Tool
Name: [LUIS]
Version: *2.0.13*
OS: *Windows 10 Pro*

## Describe the bug
When running `msbot get <SERVICE-ID-OR-NAME> | luis delete version --stdin` I get the following:

```bash
npm[15484]: src\node_file.cc:1311: Assertion `args[1]->IsInt32()' failed.
 1: 00007FF75DCE3D05
 2: 00007FF75DCBDD46
 3: 00007FF75DCBDE11
 4: 00007FF75DC85527
 5: 00007FF75E0A2AA2
 6: 00007FF75E0A3FCD
 7: 00007FF75E0A3029
 8: 00007FF75E0A2F0B
 9: 000001EA1745C6C1
```

## To Reproduce
1. Run `msbot get ServiceName | luis delete version --stdin`

## Expected behavior
The specified version in the .bot file is delete from the LUIS app.

## Additional context
Here's what my `.bot` file looks like:

```json
{
    "name": "MyBot",
    "description": "",
    "services": [
        ...
        {
            "type": "luis",
            "appId": "...",
            "authoringKey": "...",
            "name": "ServiceName",
            "id": "ServiceId",
            "region": "westus",
            "isStaging": "true",
            "subscriptionKey": "...",
            "version": "0.1.1"
        },
        ...
    ]
}
```

Might be related the the `isStaging` flag (the LUIS app was never published to prod yet).

[bug]

**Comment by cleemullins** [comment] 2018-11-15 19:08
@ahmedaashour Please take a look, so we can get this resolved in the 4.2 timeframe.

**Comment by carlosscastro** [comment] 2018-11-26 07:36
@ahmedaashour Did you take a look? Carol assigned this to you and you bounced it back but I do not understand why. What was your analysis?

**Comment by cahann** [comment] 2018-11-26 07:43
I assigned to back cause it didn’t seem to be directly related to LUIS, if it’s not P0 our DRI can check it out later this week.

**Comment by cleemullins** [comment] 2018-11-26 08:32
The LUIS tooling seems like something the team may want to consider more directly investing in.


________________________________

**Comment by cahann** [comment] 2018-11-26 08:57
Totally agree but given what we already had on our plate until end of calendar year, we are trying to squeeze this work in as much as possible but it’s not ideal cause most of the team are already heads down focusing on their Ti deliverables. Also, the team doesn’t have enough knowledge about the tools which makes the cycle slower than expected. I suggest that P0 issues continue to be handled by the ClL team until end of calendar year. Starting Va we should directly invest in the tools and account for that in our overall plan and sprints but we need to agree on a more efficient process. Next Thursday Nayer, Cez and I are meeting with Scott to close on this.

**Comment by vishwacsena** [comment] 2018-11-29 19:20
@fbeauchemin - can you share your msbot and luis version information? You can try msbot -v and luis -v to get the version information. 

I tried this on MSBot version 4.1.0 and LUIS CLI version 2.0.13 and cannot reproduce this.

**Comment by carlosscastro** [comment] 2018-12-03 21:13
@fbeauchemin could you update msbot to 4.1.0 and confirm whether this works for you? Since we cannot reproduce I'm closing it but feel free to reopen if you still repro after upgrading msbot.

**Closed by carlosscastro** 2018-12-03 21:13 UTC
Labels: 4.2, Approved, Bug, P0, msbot-cli
