### ISSUE TITLE
[Azure cli] Create msteams channel in bot using azure bot cli throws error

### ISSUE THREAD

**Issue by gpsarkar** [microsoft/botbuilder-tools#1176] opened 2019-06-12 09:19 UTC
## Tool
Name: Msbot
Version:
azure-cli (2.0.47)
botservice (0.1.1)

OS: Win10

## Describe the bug
Unable to add `msteams` channel to a bot using azure cli.
throw error : 
`Error occurred in sending request. Please file an issue on https://github.com/Microsoft/botbuilder-tools/issues
`
## To Reproduce

`az bot msteams create --name nicebot1172 --resource-group devresource`

## Expected behavior
MSTeam channel should be added to the bot

## Additional context
Bot was created using azure cli. 
--debug log for creating msteams channel

```

urllib3.connectionpool : Starting new HTTPS connection (1): management.azure.com:443
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12 HTTP/1.1" 500 2341
urllib3.util.retry : Incremented Retry for (url='/subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12'): Retry(total=3, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12
urllib3.connectionpool : Resetting dropped connection: management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12 HTTP/1.1" 500 2341
urllib3.util.retry : Incremented Retry for (url='/subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12'): Retry(total=2, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12
urllib3.connectionpool : Resetting dropped connection: management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12 HTTP/1.1" 500 2341
urllib3.util.retry : Incremented Retry for (url='/subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12'): Retry(total=1, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12
urllib3.connectionpool : Resetting dropped connection: management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12 HTTP/1.1" 500 2341
urllib3.util.retry : Incremented Retry for (url='/subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12'): Retry(total=0, connect=4, read=4, redirect=None, status=None)
urllib3.connectionpool : Retry: /subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12
urllib3.connectionpool : Resetting dropped connection: management.azure.com
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12 HTTP/1.1" 500 2341
msrest.exceptions : Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/THE_SUBSCRIPTION_ID/resourceGroups/THE_RESOURCE_GROUP/providers/Microsoft.BotService/botServices/MY_BOT_NAME123/channels/MsTeamsChannel?api-version=2018-07-12 (Caused by ResponseError('too many 500 error responses',))
Error occurred in sending request. Please file an issue on https://github.com/Microsoft/botbuilder-tools/issues
telemetry.save : Save telemetry record of length 2495 in cache

```

**Comment by dmvtech** [comment] 2019-06-12 21:09
I was able to reproduce the error. But the result is actually that Teams _does_ get connected as a channel. It's just reporting an error, due to some failures, but does not mean complete failure. 

@gpsarkar Can you confirm that it did/did not create the channel connection? (through the portal UI)

This needs to be triaged and reviewed by SDK/Tools team.

**Comment by gpsarkar** [comment] 2019-06-12 21:55
@dmvtech you are right. i just noticed that. The channel does gets connected. It just that the cli throws the error.

**Comment by stevengum** [comment] 2019-09-20 16:44
Adding this to the [Sprint 77](https://github.com/microsoft/botbuilder-tools/milestone/18) milestone.

**Comment by stevengum** [comment] 2019-11-27 19:24
I've been unable to reproduce this problem, I'm going to close the issue.

Azure-CLI has live tests that run nightly, and they haven't failed...

**Closed by stevengum** 2019-11-27 19:24 UTC
Labels: Azure CLI, Bot Services, P0, R7, bug, customer-replied-to, customer-reported
