### ISSUE TITLE
Add emulator support to enable sending of Events

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#246] opened 2018-06-25 22:16 UTC
[Events ](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-activities?view=azure-bot-service-3.0) provide a powerful way to provide out-of-band information to a Bot. 

One example is to provide contextual information about the use - i.e. what product they are looking at on a web-page or if a Bot is being embedded as part of a device experience the device can share current status of the end-user to help ensure the Bot takes this into consideration when responding. One example could be the device capabilities at a particular time (e.g. voice or text).

The Emulator should provide a way to send Events in addition to standard Message ActivityTypes. Initially to reduce the change we could expect the user to paste in some JSON and mark a given message as an Event (drop-down?) and provide an eventName.

We could then evolve into a more sophisticated experience where you can select JSON files and perhaps in situations where you need to change the items some form of editor.

**Comment by vishwacsena** [comment] 2018-06-27 22:32
I believe this is a dupe of microsoft/botframework-emulator#416. @darrenj please reactivate if you believe otherwise (prefer if you can add to the linked emulator issue so we can track this ask there).

**Closed by vishwacsena** 2018-06-27 22:32 UTC
Labels: enhancement
