### ISSUE TITLE
Dispatch create returns BadArgument: Import operation has failed

### ISSUE THREAD

**Issue by sibbl** [microsoft/botbuilder-tools#1314] opened 2019-10-07 10:32 UTC
## Tool
Name: [Dispatch]
Version: 1.5.5
OS: Windows 10 build 18362.356 

## Describe the bug

Creating a dispatch application doesn't work anymore. The tool's output is

```
Exporting services for dispatch...
Exporting app1 LUIS application...
Exported LUIS app JSON is at .\data\_L_app1.json
Exporting app2 LUIS application...
Exported LUIS app JSON is at .\data\_L_app2.json
Creating dispatch LUIS model json...
Creating training data...
Updating dispatch-app model...
Training app1...
Training app2...
Importing dispatch-app model...

ERROR
Failed importing dispatch-app app - {
  "error": {
    "code": "BadArgument",
    "message": "Import operation has failed."
  }
}
```

I created a dispatch application one week ago using a powershell script (see below).
Today I deleted it, and ran the same script again. The 

## To Reproduce
1. Create at least one luis application (in my case app1 and app2) and train it.
2. Run the following commands after setting authoring key+region and the app1 and app2's ids and names:

```
dispatch init -n "dispatch-app" --luisAuthoringKey "<yourauthoringkey>" --luisAuthoringRegion "<yourregion>"
dispatch add -t luis -i "<app1id>" -n "<app1-name>" -v 0.1 -k "<yourauthoringkey>" --intentName "app1"
dispatch add -t luis -i "<app2id>" -n "<app2-name>" -v 0.1 -k "<yourauthoringkey>" --intentName "app2"
dispatch create
```

## Expected behavior
A dispatch app should be created.

## Actual behavior
`POST /luis/api/v2.0/apps/import/?appName=dispatch-app` returns a 400 Bad Request with the errors above.

## Additional context
I've migrated my LUIS account already, just in case it might be an issue with autoring key vs. subscription based access.

As stated above, the exactly same commands ran perfectly fine 5 days ago. I also had migrated by then and both apps used for the dispatch file haven't change since then.

[bug]

**Comment by sibbl** [comment] 2019-10-07 10:33
Perhaps this might also be related to https://github.com/MicrosoftDocs/bot-docs/issues/1373

**Comment by chrimc62** [comment] 2019-10-07 18:10
@tsuwandy can you verify this if this caused by the new version of dispatch?

**Comment by tsuwandy** [comment] 2019-10-07 18:42
@sibbl, contacted LUIS team over import failure.  Will update as soon as I received a response.

**Comment by tsuwandy** [comment] 2019-10-07 20:55
@sibbl, issue has been identified and deployment is ongoing, it should be deployed before end of day tomorrow.

**Comment by tsuwandy** [comment] 2019-10-08 20:39
This issue has been fixed on LUIS side.  Please let me know if you are still seeing import failure on dispatch create.

**Closed by tsuwandy** 2019-10-08 20:39 UTC
Labels: Bot Services, customer-replied-to, customer-reported
