### ISSUE TITLE
msbot clone services fails do to "undefined" group name.

### ISSUE THREAD

**Issue by mekinney** [Microsoft/botbuilder-tools#671] opened 2018-10-18 00:12 UTC
Name: Msbot

## Describe the bug
msbot creates an incorrect resource group name when creating cloning services.

## To Reproduce

This command line is used when deploying the Virtual Assistant Bot.  It has been edited to included appID and appSecret do to other issues.

```
msbot clone services --name "TestBot" --luisAuthoringKey "myluisAuthoringKey" --folder "DeploymentScripts\en\msbotClone" --location "westus" --appId "myAppId" --appSecret "myAppSecret"

The following services will be created by this operation:
 Service                                 Location            SKU                 Resource Group
 Azure App Site Plan                     westus              S1                  TestBot
 Azure AppInsights Service               West US 2           F0                  TestBot
 Azure Blob Storage Service              westus              Standard_LRS        TestBot
 Azure Bot Service Registration          Global                                  TestBot
 Azure CosmosDB Service                  westus              1 write region      TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 (Dispatch)
 Azure QnA Maker Service                 westus              S0                  TestBot
 Azure Search Service                    westus              Standard            TestBot
 Azure WebApp Service (Bot)              westus                                  TestBot
 Azure WebApp Service (QnA)              westus                                  TestBot
Would you like to perform this operation? [y/n]y
Checking az botservice version
Fetching subscription account
Creating resources in subscription: undefined undefined
Creating Azure group [TestBot]
Using the provided ApplicationId and Secret rather than auto-provisioning
Creating Azure Bot Service [TestBot]
az bot create -g undefined --name TestBot --kind webapp --location westus --insights-location "West US 2"  --version v4 --appid 0ec87698-a1b2-4e3d-aba5-bc176f8263d9 -p "cmcfciEXUSOQ87*;*bK826+" exit code: 1
WARNING: The behavior of this command has been altered by the following extension: botservice
ERROR: Resource group 'undefined' could not be found.
```

Notice is creates a "-g undefined" option for some reason.  This happens when I use the groupname option also.

## Expected behavior
It should create the groups without erroring out.

**Comment by joseques** [comment] 2018-10-18 12:42
Please make sure that you are logged in with your Azure account with the command `az login`. You can check running `az account show` in a command prompt. 

Also a bit more information like what version of MSBot are you using and running the command with `--verbose` would be useful.

**Comment by mekinney** [comment] 2018-10-18 14:16
Thanks for the quick response.  Meant to post the verbose version, sorry about that.  Output below including version, az login information, and verbose output.  All UPPERCASE indicate placeholders for the actual values I entered into the command line (authoring id, appid, and appsecret).

```
C:\Code\AI\solutions\Virtual-Assistant\src\csharp\assistant>msbot --Version
4.0.6-87
C:\Code\AI\solutions\Virtual-Assistant\src\csharp\assistant>az account show
EnvironmentName    IsDefault    Name                            State    TenantId
-----------------  -----------  ------------------------------  -------  ------------------------------------
AzureCloud         True         Visual Studio Enterprise – MPN  Enabled  MYTENTANTID

C:\Code\AI\solutions\Virtual-Assistant\src\csharp\assistant>
C:\Code\AI\solutions\Virtual-Assistant\src\csharp\assistant>msbot clone services --verbose --name "TestBot" --luisAuthoringKey "LUISAUTHORINGKEY" --folder "DeploymentScripts\en\msbotClone" --location "westus" --appId "APPID" --appSecret "APPSECRET"
[msbot] The following services will be created by this operation:
 Service                                 Location            SKU                 Resource Group
 Azure App Site Plan                     westus              S1                  TestBot
 Azure AppInsights Service               West US 2           F0                  TestBot
 Azure Blob Storage Service              westus              Standard_LRS        TestBot
 Azure Bot Service Registration          Global                                  TestBot
 Azure CosmosDB Service                  westus              1 write region      TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 Azure LUIS Cognitive Service            westus              S0                  TestBot
 (Dispatch)
 Azure QnA Maker Service                 westus              S0                  TestBot
 Azure Search Service                    westus              Standard            TestBot
 Azure WebApp Service (Bot)              westus                                  TestBot
 Azure WebApp Service (QnA)              westus                                  TestBot
y
[msbot] Checking az botservice versionon? [y/n]
[msbot] az -v
[msbot] Fetching subscription account
[msbot] az account show
[msbot] Creating resources in subscription: undefined undefined
[msbot] Creating Azure group [TestBot]
[msbot] az group create -g TestBot -l westus
[msbot] Using the provided ApplicationId and Secret rather than auto-provisioning
[msbot] Creating Azure Bot Service [TestBot]
[msbot] az bot create -g undefined --name TestBot --kind webapp --location westus --insights-location "West US 2"  --version v4 --appid APPID -p "APPSECRET"
[msbot] az bot create -g undefined --name TestBot --kind webapp --location westus --insights-location "West US 2"  --version v4 --appid APPID -p "APPSECRET" exit code: 1
WARNING: The behavior of this command has been altered by the following extension: botservice
ERROR: Resource group 'undefined' could not be found.

[msbot] Usage: msbot clone services [options]
…
```

**Comment by joseques** [comment] 2018-10-18 19:11
Judging by your `az account show` output, it seems that you have your output format configured as a table instead of `json` format.
Try configuring it as shown [here](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest#set-the-default-output-format) using `json` as the output format.

MSBot parses the data as a JSON string and seems to be having some trouble parsing the data in table format. The output should look more like this
```bash
> az account show --output json
```
```javascript
{
  "environmentName": "AzureCloud",
  "id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "isDefault": true,
  "name": "dev-test",
  "state": "Enabled",
  "tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "user": {
    "name": "foo@bar.com",
    "type": "user"
  }
}
```

**Comment by mekinney** [comment] 2018-10-18 19:35
Yes, I have the default output set to table because it's easier for me to read.

Switching back to JSON fixed it.


Seems you should specify the  output format within the tool so changing my default doesn't impact it.

Thanks!

**Comment by carlosscastro** [comment] 2018-10-18 20:46
We will address this soon, but since this is duplicate of https://github.com/Microsoft/botbuilder-tools/issues/671, we will use that one to track the issue.

**Closed by carlosscastro** 2018-10-18 20:46 UTC
Labels: 4.2, Approved, bug, duplicate
