### ISSUE TITLE
bugbash - Zip deployment failed

### ISSUE THREAD

**Issue by mdrichardson** [Microsoft/botbuilder-tools#981] opened 2019-02-20 23:14 UTC
## Information:
* Tools Libraries: AZ CLI
* Libraries' Versions: Latest everything. AZ CLI from bug bash
* OS: Win 10

## Issue Description:
Zip deployment is reported as failing, although it appears to work.

## Reproduction Steps:
1. From bug bash, run scenario 1 with yeoman/Typescript
2. Run the `az bot publish...` command towards the end

Adding the `--debug` flag didn't really help:

![image](https://user-images.githubusercontent.com/40401643/53131601-16408c80-3522-11e9-8f9b-f09f75839e48.png)

Seems to be happening for other users and scenarios, as well.

## Expected Behavior:
No errors for a successful zip deployment.

## Actual Results:
Zip deployment reports as failed, although appears to succeed (except maybe with build).

![image](https://user-images.githubusercontent.com/40401643/53131612-1fc9f480-3522-11e9-9728-818d9b1a712f.png)

**Comment by mdrichardson** [comment] 2019-02-20 23:40
JS Sample 12. NLP-with-LUIS worked fine. I wonder if it's an issue with the generator and the post-install-script that's causing issues, since this sample does not have a post-install script.

**Comment by cleemullins** [comment] 2019-03-01 00:57
Dupe of #987

**Closed by cleemullins** 2019-03-01 00:57 UTC
Labels: Azure-cli, Dupe
