### ISSUE TITLE
Teams displaying output from QnA Maker Bot differently to QnA maker test screen and Azure 'Test in Web Chat'

### ISSUE THREAD

**Issue by Nickybuk** [microsoft/botbuilder-tools#1409] opened 2020-02-11 17:41 UTC
## Tool
Name: QnAMaker & Teams
Version: current qna maker & Microsoft Teams Version 1.3.00.2164
OS: macOs Catalina version 10.15.1

## To Reproduce
Steps to reproduce the behaviour:
1. ...Add URL to QNA KB and save and train (https://support.office.com/en-gb/article/hide-mute-or-pin-a-chat-in-teams-9aee02ef-713d-495b-8a73-9762d8e4b066)
2. ...Multi-turn Checked
3. ...questions and answers extracted, saved and published
4. ...Test in QnA Maker Portal
5. ...Test in Web Chat in Azure
6. ...Test in Teams

## Expected behaviour
I expect the format of the response from the QnA Maker Bot to be comparable with the test results (as seen in the screenshots) but the format in Teams is malformed and seems to put the images in much larger frames than the image size.

## Screenshots
The Answer as stored in the KB:
![Screenshot 2020-02-11 at 17 20 50](https://user-images.githubusercontent.com/3956917/74261274-ea01bb00-4cf2-11ea-92d3-c80cfc1706b5.png)
The question and answer in the 'Test' section on the QnA Maker portal:
![Screenshot 2020-02-11 at 16 56 07](https://user-images.githubusercontent.com/3956917/74261538-511f6f80-4cf3-11ea-91d0-fefbad61ebd1.png)
The 'Test in Web Chat' in Azure next to the same response from bot deployed locally in teams:
![Screenshot 2020-02-11 at 16 50 31](https://user-images.githubusercontent.com/3956917/74261673-7a400000-4cf3-11ea-9182-ea377c551db3.png)
The same scenario for a different question in teams:
![Screenshot 2020-02-11 at 16 26 44](https://user-images.githubusercontent.com/3956917/74261823-bbd0ab00-4cf3-11ea-9416-7c2477d119b7.png)

## Additional context
I suspect it is something to do with the images as it seems to be creating a box around the image in teams. Sorry dark mode probably doesn't help

[bug]

**Comment by clearab** [comment] 2020-02-11 23:05
Hi - I believe the issue is that inline images using Markdown formatting isn't supported in Teams. I believe you'll need to use the <img src=\"https://picsum.photos/200/300" alt=\"alt text\"></img> format.

**Comment by Nickybuk** [comment] 2020-02-12 17:02
Hi Andrew, Thank you very much for the quick reply. It seems as though inline HTML tags are unsupported in Teams too. Your suggestion of using the HTML img tag results in the plaintext html being displayed in the Teams client.
<img width="439" alt="Screenshot 2020-02-12 at 16 46 19" src="https://user-images.githubusercontent.com/3956917/74357044-37476080-4db7-11ea-8517-5e7d225162d7.png">


Are images from QnA Maker able to be rendered in the Teams client in any other way?

**Comment by clearab** [comment] 2020-02-12 20:25
We were able to test this with a regular chatbot and it worked ok - does your payload contain the closing </img> tag?

**Comment by tsuwandy** [comment] 2020-02-25 18:10
@Nickybuk, could you try adding the closing </img> tag per @clearab  suggestion above?  Thanks!

**Comment by Nickybuk** [comment] 2020-02-27 17:31
Hi, sorry for the delay in replying. The <img> element is a self closing tag requiring no closing tag. I eventually after a little trial and error discovered that the only way to load an image correctly from QnA Maker bot in the Teams Channel is to include the size and width attributes in the html img element. Im in the process of rewriting my bot to convert markdown to html to include this. This is the only way to load an image in the correct sized frame within teams that i could find

`<img src="https://support.content.office.net/en-us/media/585608f5-11ce-4851-a9d5-d3fd68a928e5.png" alt="Open chat button" width="20" height="20">`

is there a better method?

**Comment by tsuwandy** [comment] 2020-02-27 18:00
@nickybuk, i found that's what i have to do in most browsers with regard to getting an image to display properly.

**Closed by tsuwandy** 2020-02-27 18:00 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by PrajwalShambhu1990** [comment] 2021-08-30 16:16
Hello everyone - is there a way we can fix the Image display size in the Teams chatbot conversation?
 When i test the bot on QnAMaker, it display the results with correct image display as shown below.
![image](https://user-images.githubusercontent.com/50304499/131361591-14ab3a89-406f-44e0-a7d7-a66bb2aedf38.png)

The same is not displaying properly on the Teams chat window.

![image](https://user-images.githubusercontent.com/50304499/131370785-5fd600fe-9a87-43d2-b4b1-9d99fb2f455d.png)

How can we fix the image rendering issue on Teams chat window?

**Comment by clearab** [comment] 2021-08-31 16:33
Please reach out to the Teams developer support team using one of the methods outlined here: https://docs.microsoft.com/en-us/microsoftteams/platform/feedback
