### ISSUE TITLE
Unable install dispatch on mac

### ISSUE THREAD

**Issue by santifdezmunoz** [Microsoft/botbuilder-tools#862] opened 2018-12-15 16:31 UTC
## Tool
Name: Dispatch
Version: latest
OS: macOS Mojave 10.14.2

## Describe the bug
Whenever I try to install dispatch I got an error. I followed instructions on this article: https://github.com/Microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/14.nlp-with-dispatch/README.md

## To Reproduce
1. sudo npm install -g botdispatch

## Expected behavior
Having the tool installed

## Screenshots
![image](https://user-images.githubusercontent.com/114482/50045216-2efa7500-008f-11e9-9b1a-18544e79bd53.png)

**Comment by andybeak** [comment] 2018-12-16 13:11
This behaviour also happens on Linux (Linux it-00511 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by andybeak** [comment] 2018-12-16 14:36
I also encountered this problem on Ubuntu 18.04.

The problem is with the dotnet-2.1 dependency.  For some reason I can't install it globally.

So try this as a workaround until the global install is fixed:
```
npm i dotnet-2.1
npm i botdispatch
./node_modules/botdispatch/bin/dispatch.js
```

https://github.com/fearthecowboy/dotnet/issues/2

**Comment by santifdezmunoz** [comment] 2018-12-17 21:19
Thanks @andybeak, that worked perfectly.

Just an additional note. If you run the global installation after doing locally, it makes the installation globally also.

**Comment by sgellock** [comment] 2019-01-28 22:42
@santifdezmunoz what version of nodejs are you running on the machine you are trying to install botdispatch

**Comment by sgellock** [comment] 2019-02-04 19:06
I am not able to repo this using .net core 2.1, 2.2, nodejs 8.12.0

**Comment by tdurnford** [comment] 2019-02-14 06:27
@santifdezmunoz's, I followed your steps on my Mac and encountered the same error. 

<img width="691" alt="screen shot 2019-02-13 at 10 02 55 pm" src="https://user-images.githubusercontent.com/17039790/52767021-f703a580-2fdd-11e9-9630-1bc80a80cd72.png">

However, I upgraded npm from 6.5.0 to 6.8.0 and was able to install botdispatch without an issue. 

<img width="691" alt="screen shot 2019-02-13 at 10 18 36 pm" src="https://user-images.githubusercontent.com/17039790/52767032-02ef6780-2fde-11e9-94aa-1d61a866dbd6.png"> 

@santifdezmunoz could you please upgrade your package manager and let us know if that resolves your issue?

Thanks,

TJ

**Comment by ctstone** [comment] 2019-02-19 21:33
Seeing the same error on npm 6.8.0 and macOS 10.14.3.

Installing the dotnet-2.1 package locally first unblocked the install of botdispatch globally.

**Comment by tdurnford** [comment] 2019-02-21 17:06
Per the [BotBuilder Tools Readme](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Dispatch), the .NET Core runtime needs to be installed before installing botdispatch on Linux computers. It appears this is also true for Macs. 

![1af88937-2758-424c-accd-ea7f81dfa60c png](https://user-images.githubusercontent.com/17039790/53187309-b399d000-35b7-11e9-9e39-bb356e7976db.jpg)

**Comment by ctstone** [comment] 2019-02-21 17:18
Sorry, to be clear `dotnet` was already working from the command line when I hit this issue.

**Comment by tdurnford** [comment] 2019-02-21 21:44
@ctstone, are you saying that installing the dotnet-2.1 package locally should be a prereq for install botdispatch globally?

**Comment by ctstone** [comment] 2019-02-21 21:50
If anything, it feels like a workaround, and I don't understand the problem enough to say why it works. At this point i can `npm uninstall -g dotnet-2.1` and then `npn install -g dotnet-2.1` without issue, so I'm not really sure how to fully repro it.

**Comment by CoHealer** [comment] 2019-02-28 00:42
So it seems as though dotnet 2.1 must be installed locally before installing botdispatch globally but at that point dotnet 2.1 can be installed globally without affecting the botdispatch installation. @sgellock, I'm going to close this as there's a functioning work around. I'm not sure there's further investigation warranted here.

**Closed by CoHealer** 2019-02-28 00:42 UTC
Labels: Support

**Comment by sgellock** [comment] 2019-02-28 01:23
I agree.  Thanks for helping the customer and thanks for getting to the root of the issue.

**Comment by SiddharthSunchu** [comment] 2019-03-28 14:27
Downgrade your dotnet version to 2.2.103 and write npm install bot dispatch and than try to install globally. It worked for me.
