### ISSUE TITLE
error fetching subscription from Azure

### ISSUE THREAD

**Issue by awebber-chl** [Microsoft/botbuilder-tools#598] opened 2018-09-27 11:14 UTC
I'm having trouble deploying my chatbot to Azure and I think I have narrowed it down to **line 255** of **msbot-clone-services.ts**. When I issue the following command:

`msbot clone services -f deploymentScripts/msbotClone -n echobot -l "westus" --subscriptionId MYAZUREGUID`

...I get the following error:

`Command failed: az account show--subscription MYAZUREGUIDWARNING: Unable to load extension 'botservice'. Use --debug for more information.ERROR: az account: 'show--subscription' is not in the 'az account' command group. See 'az account --help'.`

If I try issuing the az account command with the additional space between "show" and "--subscriptions" then it seems to work correctly.

**Comment by vishwacsena** [comment] 2018-09-27 20:28
Dupe of #594

**Closed by vishwacsena** 2018-09-27 20:28 UTC
Labels: azure-cli
