### ISSUE TITLE
Luis - Publish to Azure Subscription (Not starter key)

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#472] opened 2018-09-13 22:53 UTC
**Describe the bug**
"Luis publish version" does not give option to include the subscription key for an Azure Luis instance and defaults to the starter key. This requires the user to manually go into the portal to publish to the correct service.

**Context**
Luis Version 2.0.11-2.5.12

**Comment by tomlm** [comment] 2018-09-14 01:29
I think the current behavior is correct.  

luis publish version --appId <string> --versionId <version> --region <region> --staging --authoringKey <authoringKey>


What I *think* you are complaining about is that you can't define a endpointKey for a region from the LUIS command line tool.  That is true, and it's because the LUIS team doesn't have that defined in their API.  

There are only 2 ways to get your endpointKey set up right
*  you have to go into the portal.

 OR 

*  You mark your application as public, in which case a LUIS subscriptionKey for the same region as the endpoint can be used as the endpointKey. 

Until they give us an API, I have been using the latter approach.  msbot clone actually sets the LUIS app as public for this very reason.

**Comment by vishwacsena** [comment] 2018-09-14 07:02
Dupe of #205

**Closed by vishwacsena** 2018-09-14 07:02 UTC
