### ISSUE TITLE
Add Path to LU file within msbot recipe

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#540] opened 2018-09-19 17:01 UTC
Scenario: Developer has a recipe with associated LUIS and QNA files. However these are separate from the source LU files meaning the two have to be kept in sync and duplicating the same content across two files.

Adding a "path" to the recipe entry to a .LU file would enable this to be pulled in at deployment time ensuring the most up to date version is used.

**Comment by vishwacsena** [comment] 2018-09-22 04:50
Dupe of #475

**Closed by vishwacsena** 2018-09-22 04:50 UTC
Labels: Backlog, msbot-cli
