### ISSUE TITLE
AZ CLI: az bot publish does not include referenced class libraries in solution

### ISSUE THREAD

**Issue by joetossell29** [Microsoft/botbuilder-tools#1005] opened 2019-03-05 11:07 UTC
## Tool
Name: AZ CLI botservice
Version: AZ CLI: 2.0.59
OS: Windows 10

## Describe the bug
Referenced class libraries are not included in the deployment when using az bot publish command as generated by msbot clone

## To Reproduce
1. msbot clone to setup up resources
2. Create class library and reference from bot
3. Run generated publish.cmd
4. Deployment fails:
```
{
"log_time": "2019-03-05T10:12:02.5513332Z",
"id": "",
"message": "Command: "D:\home\site\deployments\tools\deploy.cmd"",
"type": 0,
"details_url": null
},
{
"log_time": "2019-03-05T10:12:04.1342578Z",
"id": "",
"message": "Handling ASP.NET Core Web Application deployment.",
"type": 0,
"details_url": null
},
{
"log_time": "2019-03-05T10:12:07.3952989Z",
"id": "",
"message": "  Skipping project "D:\local\Temp\zipdeploy\{solution name}\{class library}.csproj" because it was not found.",
"type": 0,
"details_url": null
},
```

## Expected behavior
Publishing a bot should include class libraries as required

[bug]

**Comment by dmvtech** [comment] 2019-03-15 21:45
@joetossell29  I'm taking a look.

**Comment by dmvtech** [comment] 2019-03-18 22:52
@joetossell29 I am unable to reproduce the failure. I'm not sure what I'm doing different. How are you referencing the class library? Are you just referencing the project using `Dependencies->Add Reference-> Solution`?

**Comment by CoHealer** [comment] 2019-03-21 22:33
@joetossell29, do you still require assistance? You haven't followed up on this in 16 days.

**Comment by dmvtech** [comment] 2019-03-25 16:55
Closing due to no action on this. If still an issue, please reopen.

**Closed by dmvtech** 2019-03-25 16:55 UTC
Labels: Support
