### ISSUE TITLE
[P0] LUIS CLI does not work when installed from MyGet feed [Windows]

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#411] opened 2018-09-04 20:58 UTC
On a windows 10 device - 

> npm uninstall -g luis-apis
> npm config set registry https://botbuilder.myget.org/F/botbuilder-tools-daily/npm/
> npm i -g luis-apis
C:\Users\vkannan\AppData\Roaming\npm\luis -> C:\Users\vkannan\AppData\Roaming\npm\node_modules\luis-apis\bin\luis
+ luis-apis@2.0.10-4
added 111 packages in 24.106s

C:\repos\BotBuilder-Samples\javascript_nodejs\2.echobot-with-counter>luis
module.js:549
    throw err;
    ^

Error: Cannot find module '../lib/luisAuthoring'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\vkannan\AppData\Roaming\npm\node_modules\luis-apis\bin\luis:12:27)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by enzocanoo** [comment] 2018-09-05 18:49
Fixed with #412. The cause of the problem was an issue with the publish script.

**Closed** 2018-09-10 17:27 UTC
Labels: Approved, Next-Iteration, luis-cli
