### ISSUE TITLE
msbot clone command creates malformed bot file

### ISSUE THREAD

**Issue by Zerryth** [Microsoft/botbuilder-tools#997] opened 2019-02-27 00:55 UTC
## Tool
Name: msbot 4.3.3

## Describe the bug
Running `msbot clone` to start up a sample creates broken bot file, with `services` malformed

## To Reproduce
1. `git clone https://github.com/Microsoft/BotBuilder-Samples.git`
2. Navigate to a sample. For me, I did `14.nlp-with-dispatch` and `13.basic-bot` in node
3. Run clone command provided in readme to provision services
  * `msbot clone services --name "AshleyHopefullyNotBrokenNlpBot" --luisAuthoringKey xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --code-dir "." --location westus --sdkLanguage "Node" --folder deploymentScripts/msbotClone --verbose`

## Expected behavior
For bot file to clone with properly-shaped objects for the different `services` in the `.bot` file

## Actual behavior
`.bot` file malforms and creates what appears to be an error, printed out letter-by-letter as key-values to an object in the `services` array

## Screenshots
_zoomed out: 485-line long `.bot` file_ (should be around 60-lines long for `14.nlp-with-dispatch`)
![image](https://user-images.githubusercontent.com/35248895/53457382-12f84580-39e7-11e9-8d19-5843b7e46c8b.png)

_zoomed in: `.bot` file seems to be printing an error as an object in services_
![image](https://user-images.githubusercontent.com/35248895/53457435-43d87a80-39e7-11e9-93b0-ac1b7081b8bd.png)

## Additional Context

The `msbot clone` command does complete seemingly successfully--spits out your bot file secret, gives you prompt "`Done.`" at the end.

When I tried `npm i` then `npm start` though, it warns that the `blahblah LUIS model not found in .bot file. Please ensure you have all required LUIS models created and available in the .bot file` that lead me down the path to check the `.bot` file and find it malformed

[bug]

**Comment by munozemilio** [comment] 2019-03-14 20:32
I was not able to reproduce this issue.
Ashley's issue got fixed by upgrading cli tools.
 Closing this bug.

**Closed** 2019-03-14 20:32 UTC
Labels: 4.4, BEST BUG EVER, Bug, For The Win, P0
