### ISSUE TITLE
Creating bot service through CLI fails

### ISSUE THREAD

**Issue by ukphillips** [Microsoft/botbuilder-tools#268] opened 2018-07-17 12:21 UTC
**Describe the bug**
When creating the bot through the CLI per the instructions listed here: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tools-az-cli?view=azure-bot-service-3.0 the CLI prompts me to login again using the device code, upon completion of logging in, I receive the following message: "Unable to provision appid and password for supplied credentials". This was also tried locally and from the cloud shell

**To Reproduce**
1.  execute: az bot create --resource-group "sandbox" --name "uniquedeploykris" --kind "webapp" --description "description-of-my-bot" --debug

**Expected behavior**
Would not expect the CLI to have me authenticate again, and for the Bot to be created without an error.

**Screenshots**
CLI Output (removed start up CLI module logs):
```
Getting management service client client_type=AzureBotService
adal-python : 7cf50588-629b-426d-8d13-ca131fe0caa6 - Authority:Performing instance discovery: ...
adal-python : 7cf50588-629b-426d-8d13-ca131fe0caa6 - Authority:Performing static instance discovery
adal-python : 7cf50588-629b-426d-8d13-ca131fe0caa6 - Authority:Authority validated via static instance discovery
adal-python : 7cf50588-629b-426d-8d13-ca131fe0caa6 - CodeRequest:Getting user code info.
urllib3.connectionpool : Starting new HTTPS connection (1): login.windows.net:443
urllib3.connectionpool : https://login.windows.net:443 "POST /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/devicecode?api-version=1.0 HTTP/1.1" 200 455
adal-python : 7cf50588-629b-426d-8d13-ca131fe0caa6 - OAuth2Client:Get Device Code Server returned this correlation_id: 7cf50588-629b-426d-8d13-ca131fe0caa6
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code AWFC6MF9C to authenticate.
adal-python : 7cf50588-629b-426d-8d13-ca131fe0caa6 - Authority:Instance discovery/validation has either already been completed or is turned off: ...
adal-python : 7cf50588-629b-426d-8d13-ca131fe0caa6 - TokenRequest:Getting a token via device code
urllib3.connectionpool : Starting new HTTPS connection (1): login.windows.net:443
urllib3.connectionpool : https://login.windows.net:443 "POST /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token HTTP/1.1" 400 404
urllib3.connectionpool : Starting new HTTPS connection (1): login.windows.net:443
urllib3.connectionpool : https://login.windows.net:443 "POST /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token HTTP/1.1" 400 404
urllib3.connectionpool : Starting new HTTPS connection (1): login.windows.net:443
urllib3.connectionpool : https://login.windows.net:443 "POST /72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token HTTP/1.1" 200 3747
adal-python : 7cf50588-629b-426d-8d13-ca131fe0caa6 - OAuth2Client:Get token with device code Server returned this correlation_id: 7cf50588-629b-426d-8d13-ca131fe0caa6
adal-python : 7cf50588-629b-426d-8d13-ca131fe0caa6 - TokenRequest:Storing retrieved token into cache
adal-python : 7cf50588-629b-426d-8d13-ca131fe0caa6 - CacheDriver:Adding entry AccessTokenId: b'***************REDACTED***************', RefreshTokenId: b'*****************REDACTED***************'
adal-python : 7cf50588-629b-426d-8d13-ca131fe0caa6 - CacheDriver:Added entry is MRRT
urllib3.connectionpool : Starting new HTTPS connection (1): dev.botframework.com:443
urllib3.connectionpool : https://dev.botframework.com:443 "POST /api/botApp/provisionConvergedApp?name=uniquedeploykris HTTP/1.1" 500 101
Unable to provision appid and password for supplied credentials
```
**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - CLI Version 2.0.41

**Additional context**
N/A

**Comment by ukphillips** [comment] 2018-07-17 12:31
Sorry, looks like this is a duplicate of https://github.com/Microsoft/botbuilder-tools/issues/183

**Comment by vishwacsena** [comment] 2018-07-17 18:22
Closing as dupe of #183

**Closed by vishwacsena** 2018-07-17 18:22 UTC
