### ISSUE TITLE
Invalid .bot file gives a confusing error message 

### ISSUE THREAD

**Issue by jameslew** [Microsoft/botbuilder-tools#479] opened 2018-09-14 20:08 UTC
**Describe the bug**
In related bug, the .bot file was created using Windows path separators instead of Linux separators.  When I tried to npm start, the command line complained that I hadn't set environment variables when the real problem was that my environment variables had a problem.

**To Reproduce**
1. Edit a .bot file to put the wrong path separator in for Bot File path
2. Try to run with NPM start

jameslew@JAMESLEW1:/mnt/c/repos/foo/BaconBot$ npm start

> echobot-with-counter@1.0.0 start /mnt/c/repos/foo/BaconBot
> node index.js

Error reading bot file. Please ensure you have valid botFilePath and botFileSecret set for your environment
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! echobot-with-counter@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the echobot-with-counter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jameslew/.npm/_logs/2018-09-14T19_54_54_421Z-debug.log

**Expected behavior**
Error indicating which of my environment variables were set improperly instead of me thinking the file was somehow missing.

**Comment by tomlm** [comment] 2018-09-15 20:48
I don't understand your repo case.

**Comment by vishwacsena** [comment] 2018-09-16 17:52
Dupe of #340

**Closed by vishwacsena** 2018-09-16 17:52 UTC
Labels: Next-Iteration, bug

**Comment by jameslew** [comment] 2018-09-16 20:27
Sorry - missing key point is that this was all being performed from a Linux distro in Windows.  When we do the AZ Bot Download, we create the .env using "\" as the path separator, which isn't recognized by Linux.  We need to do the appropriate separator for the OS env.
