### ISSUE TITLE
[LUIS] Getting error while exporting from remote to local

### ISSUE THREAD

**Issue by SreekanthOAuth** [microsoft/botbuilder-tools#1389] opened 2019-12-04 13:05 UTC
## Tool
Name: LUIS & LUISDOWN
Version: *tool version*
OS: *os version*

## Describe the bug
Getting below exception while exporting from remote,

The versions - Export application version Operation under LUIS Programmatic APIs v2.0 API is not supported with the current subscription key and pricing tier LUIS.S0.

LUIS Command Line Interface - © 2018 Microsoft Corporation

Exports a LUIS application to JSON format.

Usage:
luis export version --appId <string> --versionId <string>

Command arguments are:
 --appId <string> (required)    The application ID.
 --versionId <string>           The version ID.
 (required)

Configuration and Overrides:
 --appId                        Specifies the public LUIS application id. Overrides the .luisrc value
                                and the LUIS_APP_ID environment variable.
 --authoringKey                 Specifies the LUIS authoring  key (from luis.ai portal user settings
                                page). Overrides the .luisrc value and the LUIS_AUTHORING_KEY
                                environment variable.
 --subscriptionKey              Specifies the LUIS subscriptionKey. Overrides the .luisrc value and
                                the LUIS_SUBSCRIPTION_KEY environment variable.
 --versionId                    Specifies the version id. Overrides the .luisrc value and the
                                LUIS_VERSION_ID environment variable.
 --region                       Specifies the authoring region for all requests.
                                [westus|westeurope|australiaeast] Overrides the .luisrc value and the
                                LUIS_REGION environment variable.
 --cloud                        Specifies the cloud region for all requests. [com|us] Overrides the
                                .luisrc value and the LUIS_CLOUD environment variable.
 --stdin                        Pull in service keys from stdin in the format of that is the output
                                of: msbot get service
 --prefix                       Appends [luis-apis] prefix to all messages

Global Arguments:
 --help,    -h                  Prints this help file.
 --version, -v                  Prints the version of this cli tool
 --force,   -f                  Do not prompt for confirmation, force the operation
 --!                            Dumps all documented commands to the console with descriptions

Sorry, unable to parse stdin as JSON!

 {}

Stopping further processing.
> Parsing erpskill LU file ...

WARN: Unrecognized LUIS locale. Supported locales are - en-us,fr-ca,zh-cn,nl-nl,fr-fr,de-de,it-it,ja-jp,ko-kr,pt-br,es-es,es-mx,tr-tr

Below code is causing issue

`foreach ($luisApp in $models.languageModels) {
            $culture = (luis get application `
                    --appId $luisApp.appId `
                    --authoringKey $luisApp.authoringKey `
                    --subscriptionKey $luisApp.subscriptionKey `
                    --region $luisApp.authoringRegion | ConvertFrom-Json).culture
            Write-Host "> culture ... $($culture)"
            Write-Host "> Updating local $($luisApp.name).lu file ..."
            luis export version `
                --appId $luisApp.appId `
                --versionId $luisApp.version `
                --region $luisApp.authoringRegion `
                --authoringKey $luisApp.authoringKey | ludown refresh `
                --stdin `
                -n "$($luisApp.name).lu" `
                -o $(Join-Path $luisFolder $langCode)

            # # Parse LU file
			$id = $luisApp.name
			$outFile = "$($id).luis"
			$outFolder = $(Join-Path $luisFolder $langCode)
			$appName = "$($name)$($langCode)_$($id)"

			Write-Host "> Parsing $($luisApp.name) LU file ..."
			ludown parse toluis `
				--in $(Join-Path $outFolder "$($luisApp.name).lu") `
				--luis_culture $culture `
				--out_folder $(Join-Path $luisFolder $langCode) `
				--out "$($luisApp.name).luis"
            if ($useLuisGen) {
                Write-Host "> Running LuisGen for $($luisApp.name) app ..."
                $luPath = $(Join-Path $luisFolder $langCode "$($luisApp.name).lu")
                RunLuisGen -lu_file $(Get-Item $luPath) -outName "$($luisApp.name)" -outFolder $lgOutFolder
            }

            # Add the LUIS application to the dispatch model. 
            # If the LUIS application id already exists within the model no action will be taken
            if ($dispatch) {
                Write-Host "> Adding $($luisApp.name) app to dispatch model ... "
                (dispatch add `
                    --type "luis" `
                    --name $luisApp.name `
                    --id $luisApp.appid  `
                    --region $luisApp.authoringRegion `
                    --intentName "l_$($luisApp.name)" `
                    --dispatch $(Join-Path $dispatchFolder $langCode "$($dispatch.name).dispatch") `
                    --dataFolder $(Join-Path $dispatchFolder $langCode))  2>> $logFile | Out-Null
        
            }
        }`

## To Reproduce
1. Create LUIS model
2. Export Sample Assistant from [here](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant)
3. And update cognitive models with LUIS model
4. Run the update_cognitive_models.ps1

## Expected behavior
Should export the .lu file.

## Additional context

[bug]

**Comment by dmvtech** [comment] 2019-12-06 17:22
I'm seeing if I can reproduce this issue. I'll let you know if I have any questions.

**Comment by dmvtech** [comment] 2019-12-17 00:10
Hi @SreekanthOAuth What versions of luis and ludown are you using that reproduces this issue with?

I'm wondering if this is related indirectly related to the other issue with qnamaker tool. i.e. The tool is creating bad JSON and therefore fails on a later step.

Can you confirm that you can still reproduce this issue and if so, let me know what versions of the tools you are using.

**Comment by SreekanthOAuth** [comment] 2019-12-17 05:32
@dmvtech , the versions of 

1. Ludown - 1.4.0
2. Luis - 2.6.2

I'm still seeing the same exception even after updating the qnamaker to 1.3.3.

Thanks,
Sreekanth

**Comment by dmvtech** [comment] 2019-12-18 00:02
Looks like ludown has that same deprecation message. I'm wondering if maybe that got added to the .json file somehow. Can you check your .json files in your `Deployment\Resources\LU\<language> `folder and see if there is the following message in them (or anything that seems to be invalid JSON):

>  This tool has been deprecated.
>  All functionality was ported over to the new BF CLI.
>  To learn more visit https://aka.ms/NewBFCLI

Possibly also try uninstalling ludown and using the previous version (at least as a test for now):
`npm i ludown@1.3.4`

**Comment by SreekanthOAuth** [comment] 2019-12-18 10:02
@dmvtech , There is no same deprecation message in files

I have updated the ludown with 1.3.4, but still seeing the same error and also suggesting to update it to 1.4.0. Below is the total log

useLuisGen False...and RemoteToLocal True

The apps - Get application info Operation under LUIS Programmatic APIs v2.0 is not supported with the current subscription key and pricing tier LUIS.S0.

LUIS Command Line Interface - © 2018 Microsoft Corporation

Gets the application info.

Usage:
luis get application --appId <string>

Command arguments are:
 --appId <string>           The application ID.
 (required)
 --msbot                    (OPTIONAL) Format the output as json for piping into msbot connect luis
                            command

Configuration and Overrides:
 --appId                    Specifies the public LUIS application id. Overrides the .luisrc value and
                            the LUIS_APP_ID environment variable.
 --authoringKey             Specifies the LUIS authoring  key (from luis.ai portal user settings
                            page). Overrides the .luisrc value and the LUIS_AUTHORING_KEY environment
                            variable.
 --subscriptionKey          Specifies the LUIS subscriptionKey. Overrides the .luisrc value and the
                            LUIS_SUBSCRIPTION_KEY environment variable.
 --versionId                Specifies the version id. Overrides the .luisrc value and the
                            LUIS_VERSION_ID environment variable.
 --region                   Specifies the authoring region for all requests.
                            [westus|westeurope|australiaeast] Overrides the .luisrc value and the
                            LUIS_REGION environment variable.
 --cloud                    Specifies the cloud region for all requests. [com|us] Overrides the
                            .luisrc value and the LUIS_CLOUD environment variable.
 --stdin                    Pull in service keys from stdin in the format of that is the output of:
                            msbot get service
 --prefix                   Appends [luis-apis] prefix to all messages

Global Arguments:
 --help,    -h              Prints this help file.
 --version, -v              Prints the version of this cli tool
 --force,   -f              Do not prompt for confirmation, force the operation
 --!                        Dumps all documented commands to the console with descriptions

> Updating local common.lu file ...

     Update available 1.3.4 -> 1.4.0
     Run npm i -g ludown to update.

The versions - Export application version Operation under LUIS Programmatic APIs v2.0 is not supported with the current subscription key and pricing tier LUIS.S0.

LUIS Command Line Interface - © 2018 Microsoft Corporation

Exports a LUIS application to JSON format.

Usage:
luis export version --appId <string> --versionId <string>

Command arguments are:
 --appId <string> (required)    The application ID.
 --versionId <string>           The version ID.
 (required)

Configuration and Overrides:
 --appId                        Specifies the public LUIS application id. Overrides the .luisrc value
                                and the LUIS_APP_ID environment variable.
 --authoringKey                 Specifies the LUIS authoring  key (from luis.ai portal user settings
                                page). Overrides the .luisrc value and the LUIS_AUTHORING_KEY
                                environment variable.
 --subscriptionKey              Specifies the LUIS subscriptionKey. Overrides the .luisrc value and
                                the LUIS_SUBSCRIPTION_KEY environment variable.
 --versionId                    Specifies the version id. Overrides the .luisrc value and the
                                LUIS_VERSION_ID environment variable.
 --region                       Specifies the authoring region for all requests.
                                [westus|westeurope|australiaeast] Overrides the .luisrc value and the
                                LUIS_REGION environment variable.
 --cloud                        Specifies the cloud region for all requests. [com|us] Overrides the
                                .luisrc value and the LUIS_CLOUD environment variable.
 --stdin                        Pull in service keys from stdin in the format of that is the output
                                of: msbot get service
 --prefix                       Appends [luis-apis] prefix to all messages

Global Arguments:
 --help,    -h                  Prints this help file.
 --version, -v                  Prints the version of this cli tool
 --force,   -f                  Do not prompt for confirmation, force the operation
 --!                            Dumps all documented commands to the console with descriptions

Sorry, unable to parse stdin as JSON!

 {}


Stopping further processing.
> Parsing common LU file ...

     Update available 1.3.4 -> 1.4.0
     Run npm i -g ludown to update.

WARN: Unrecognized LUIS locale. Supported locales are - en-us,fr-ca,zh-cn,nl-nl,fr-fr,de-de,it-it,ja-jp,ko-kr,pt-br,es-es,es-mx

undefined
Stopping further processing.

Thanks,
Sreekanth

**Comment by dmvtech** [comment] 2019-12-18 19:08
Thanks @SreekanthOAuth 

Are you using the prediction key or the authoring key (often labled starter) for LUIS? You should be using a authoring one. Below you can see how I have one predction only key, one that is both (first image) and one authoring only (second image). You can see how both keys for the starting/authoring are the same (green).

![image](https://user-images.githubusercontent.com/43397658/71115037-e552d780-2185-11ea-9e5a-6142bf29fb6f.png)

![image](https://user-images.githubusercontent.com/43397658/71115246-5abea800-2186-11ea-8e11-38d198520793.png)

**Comment by SreekanthOAuth** [comment] 2019-12-19 04:05
Hi @dmvtech , I don't see two tabs in my account. 

![image](https://user-images.githubusercontent.com/24246902/71144106-db42de80-2242-11ea-8cd9-7ae3d62c4267.png)

Thanks,
Sreekanth

**Comment by dmvtech** [comment] 2019-12-19 16:19
> Is this new feature which would come after migration?

It might be. 

I think that is the problem; you are using the prediction key, but you need to use the starter/authoring key for _making changes_ (anything making LUIS api calls). 

The assistant or skill can of course use the prediction key from configuration for normal prediction execution.

**Comment by dmvtech** [comment] 2019-12-23 19:15
Hi @SreekanthOAuth any luck using the auth/starter key?

**Comment by dmvtech** [comment] 2020-01-01 18:14
Closing this as idle. Please reopen if further assistance is needed.

**Closed by dmvtech** 2020-01-01 18:14 UTC
Labels: Bot Services, customer-replied-to, customer-reported
