### ISSUE TITLE
Chatdown - Missing "from" property in first Activity

### ISSUE THREAD

**Issue by justinwilaby** [Microsoft/botbuilder-tools#741] opened 2018-11-07 00:15 UTC
The Chatdown CLI sometimes creates the first activity with null `from` properties which breaks the Emulator (and probably WebChat).

The left-hand transcript was created with Chatdown v1.0.9 while the right-hand transcript was created with v1.0.11:
![image](https://user-images.githubusercontent.com/2652885/48102270-1d47c700-e1df-11e8-96cb-5c8bb489483f.png)

**Comment by tonyanziano** [comment] 2018-11-07 00:19
Related issue: #702

**Comment by justinwilaby** [comment] 2018-11-07 00:38
I got background from @vishwacsena on this issue. This is per protocol and WAD. Emulator and WebChat need to adopt the changes.

**Comment by vishwacsena** [comment] 2018-11-07 21:19
Dupe of #702. The right fix here is in webchat and so assigned that to @compulim

**Closed by vishwacsena** 2018-11-07 21:19 UTC
