### ISSUE TITLE
Dispatch Eval terminates with Object Reference error

### ISSUE THREAD

**Issue by dkonyayev** [microsoft/botbuilder-tools#1336] opened 2019-10-30 13:51 UTC
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: 1.5.7
OS: Win 10 PRO

## Describe the bug
Running dispatch eval terminates with error.

## To Reproduce
call dispatch eval --luisSubscriptionKey "<mykey>" --luisSubscriptionRegion westus

## Expected behavior
Eval report

## Screenshots

call dispatch eval --luisSubscriptionKey "<mykey>" --luisSubscriptionRegion westus
Model evaluation may take a while. Please wait...
Running cross validation...
Updating MyProject_fold000 model...
Updating MyProject_fold001 model...
Updating MyProject_fold002 model...
Updating MyProject_fold003 model...
Updating MyProject_fold004 model...
Training MyProject_fold000 model...
Training MyProject_fold001 model...
Training MyProject_fold002 model...
Training MyProject_fold003 model...
Training MyProject_fold004 model...
Publishing MyProject_fold000 model...
Testing MyProject_fold000 model...
Processing 100 predictions out of 1377
Processing 200 predictions out of 1377
Processing 300 predictions out of 1377
Processing 400 predictions out of 1377
Processing 500 predictions out of 1377
Processing 600 predictions out of 1377
Processing 700 predictions out of 1377
Processing 800 predictions out of 1377
Processing 900 predictions out of 1377
Processing 1000 predictions out of 1377
Processing 1100 predictions out of 1377
Processing 1200 predictions out of 1377
Processing 1300 predictions out of 1377

ERROR
Object reference not set to an instance of an object.

------
EVAL
Usage: dispatch eval

Run evaluation of the newly created LUIS application from the create command

## Additional context

[bug]

**Comment by dmvtech** [comment] 2019-10-30 17:55
I can reproduce in dispatch version `1.5.4`

**Comment by tsuwandy** [comment] 2019-10-31 20:42
@dkonyayv, @dmvtech, we have a new version coming to fix the throttling from LUIS prediction during evaluation.

**Comment by tsuwandy** [comment] 2019-10-31 22:08
@dkonyayev , botdispatch 1.5.8 is just published.  Please let us know if you are still running into this issue.  Thanks!

**Comment by singzzz** [comment] 2019-11-07 11:12
@tsuwandy It looks like I am getting the same issue when running the refresh command in 1.5.8, have raised a new ticket #3154

**Comment by tsuwandy** [comment] 2019-11-13 17:10
@singzzz, @dkonyayev, I haven't been able to repro, is this still happening?

**Comment by tsuwandy** [comment] 2019-11-14 19:06
@singzzz, @dkonyayev, closing this as I couldn't repro.  Please reopen if it's still happening on your side.

**Closed by tsuwandy** 2019-11-14 19:06 UTC
Labels: Bot Services, customer-replied-to, customer-reported
