### ISSUE TITLE
msbot clone: qnamaker url is missing "/qnamaker" suffix segment

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#502] opened 2018-09-17 18:04 UTC
**Describe the bug**
The output hostname value from msbot clone for qnamaker is missing "/qnamaker" at the end. The bot cannot connect to qnamaker without it.

Version: 2.0.4-14

**Comment by tomlm** [comment] 2018-09-17 23:59
I think the current behavior is by design. QnAMaker passes around hostname without the /QnAMaker. We should change the QnARecognizer code to add the appropriate suffix.

**Comment by vishwacsena** [comment] 2018-09-18 00:35
We should be consistent across our tools. This command adds /qnamaker to the .bot file... and i can just directly consume the hostname in my code .. 

> qnamaker create kb --in cognitiveModels\sample.qna --subscriptionKey <YOUR-QNA-SUBSCRIPTION-KEY> --msbot | msbot connect qna --stdin --name sample.qna

**Comment by tomlm** [comment] 2018-09-18 01:47
**dotnet**
- [x] PR https://github.com/Microsoft/botbuilder-dotnet/pull/965
- [ ] committed

**js**
- [x] PR https://github.com/Microsoft/botbuilder-js/pull/448
- [ ] committed

**Closed** 2018-09-18 02:14 UTC
Labels: Approved, Next-Iteration, by design, msbot-cli
