### ISSUE TITLE
Dispatch Refresh working Locally on Windows10 but not on Windows Server 2016

### ISSUE THREAD

**Issue by Stikemanley** [microsoft/botbuilder-tools#1138] opened 2019-05-13 21:11 UTC
## Tool
name: dispatch
version: 4.6.1 (both OSes)
OSes: Windows 10, Windows Server 2016

## Issue Description:
I have a bot utilizing both QnA and LUIS models with a dispatcher. I am able to run a dispatch refresh command on Windows 10 successfully.  It Exports all models, then updates, imports, and trains all models including the new Dispatch model.

I am attempting to set up a scheduled refresh (Using Task Scheduler) on a production server (the Windows Server 2016) however no matter what I do the refresh fails.

## Commands Example:
There are slight differences of course between the two environments. 
local (win10)```dispatch refresh --dataFolder <folder>```
prod(winserver2016) is a scheduled Task to start a program with the following params
* Program/script: C:\Users\autoadmin\AppData\Roaming\npm\dispatch.cmd
* Arguments: refresh --dataFolder <folder> > dispatch-logs.log 2>&1
* Start in: folder containing Dispatch Model directories 

## Reproduction Steps:
1. Kick off the Task Scheduled task in the WinServer2016 UI
2. Wait to finish
3. Review logs files for the following error

Exporting services for dispatch...
Exporting ConnectionSkills-PROD-Model LUIS application...
Exporting Utilities-PROD-Model LUIS application...
Exporting SearchSkills-PROD-Model LUIS application...
Exporting Smalltalk-PROD-QnA QnA kb...
Exporting MicroSkills-PROD-QnA QnA kb...
Exporting ITKB-Public-PROD-QnA QnA kb...
Exporting ITKB-Internal-PROD-QnA QnA kb...
Creating dispatch LUIS model json...
Creating training data...
WARNING: Number of samples in '<path>\data\_experiments\model_008\train.txt' that were used by multiple categories: 18
WARNING: Number of samples in '<path>\data\_experiments\model_008\cv5\fold000\train.txt' that were used by multiple categories: 11
WARNING: Number of samples in '<path>\data\_experiments\model_008\cv5\fold001\train.txt' that were used by multiple categories: 11
WARNING: Number of samples in '<path>\data\_experiments\model_008\cv5\fold001\test.txt' that were used by multiple categories: 2
WARNING: Number of samples in '<path>\data\_experiments\model_008\cv5\fold002\train.txt' that were used by multiple categories: 13
WARNING: Number of samples in '<path>\data\_experiments\model_008\cv5\fold003\train.txt' that were used by multiple categories: 10
WARNING: Number of samples in '<path>\data\_experiments\model_008\cv5\fold003\test.txt' that were used by multiple categories: 1
WARNING: Number of samples in '<path>\data\_experiments\model_008\cv5\fold004\train.txt' that were used by multiple categories: 10
WARNING: Number of samples in '<path>\data\_experiments\model_008\cv5\fold004\test.txt' that were used by multiple categories: 2
Updating Dispatch-PROD-Model model...
Importing Dispatch-PROD-Model model...

ERROR
Failed importing latest version of Dispatch-PROD-Model app

------
REFRESH
Usage: dispatch refresh [options]

Retrain and republish existing LUIS dispatch application after modifications. Dispatch application id will be unchanged.

Options:

   -v, --version           [Optional] Dispatch LUIS app version. A new version will be created if param value is different than previously created version.
   -b, --bot               [Optional] Path to .bot file or bot services json file
   -s, --secret            [Optional] Secret used to encrypt/decrypt .bot file
   --dispatch              [Optional] Path to .dispatch file
   --publishToStaging      [Optional] Default to false.
   --dataFolder            [Optional] Dispatch working directory

## Debug Attempts

* If I take the .dispatch file and move it locally it works fine.
* If i take the .dispatch file and import it using LUIS UI it works fine

**Comment by tsuwandy** [comment] 2019-05-15 20:02
@Stikemanley, what's in dispatch.cmd script?  Could you make sure that it has the "--dataFolder {dispatchWorkingFolder}" for all the commands?  

Alternatively, if you only need to refresh previously create Dispatch in the Win Server 2016, you could put the .dispatch file in the same folder as dispatch.cmd script (where the only thing in it is the "dispatch refresh" command) and it should work.    I assume the scheduled task is to there to pick up changes from the Dispatch sources (other LUIS apps or QnA kbs).  

Will close this issue as this doesn't sound like a Dispatch related issue but let us if you are still having problem with it.

**Closed by tsuwandy** 2019-05-15 20:02 UTC

**Comment by Stikemanley** [comment] 2019-05-16 01:59
Hi Tien!

Nothing in the dispatch.cmd script. That’s just the path to the dispatch executable. We haven’t installed the dispatch globally on the windows 2016 server. It behaves the same with the same path and just <path>/dispatch as it does <path>/dispatch.cmd

Another note, we manually imported the .dispatch file into LUIS and it worked perfectly, therefore I don’t believe it’s a conflict of entities etc... between models. 

Thanks,
Mike

**Comment by tsuwandy** [comment] 2019-05-16 02:10
Thanks Mike.  .dispatch file is a dispatch configuration file, not LUIS json file.  Did you meant importing {DispatchName}.json file to LUIS?   

Back to the "refresh" issue, did you try copying the {DispatchName}.dispatch file to where the dispatch executable is and run the command "dispatch.cmd refresh"?  This should work.  The refresh command needs existing .dispatch file since it needs to figure out the app id to refresh, the source apps/kbs, authoring key, etc.

Let me know if this is not clear.  Thanks!

**Comment by Stikemanley** [comment] 2019-05-20 18:28
Hello Tien,

Thank you for getting back to me. I've tried moving the .dispatch file to
the same directory as dispatch.cmd. I receive the same error message:

[image: image.png]

I didn't expect this to be the issue as it was able to export all the
necessary services previously as well.

Any other thoughts?

I know its not an issue with the different models themselves as I was able
to manually import and train this dispatcher using the {dispatch name}.json
file.

Thanks,
Mike

**Comment by Stikemanley** [comment] 2019-05-20 19:00
Hi Tien,

What was happening was I was using an older .json file to import. When I
found the latest version inside the data folder created by dispatch.cmd It
gave me another message which was in essense "You don't have entities with
the same name". What had happened was we used datetimeV2 in patterns in two
different models.

This seems like something that should absolutely be covered. We should be
able to use the same prebuilt entities in all of our models. Additionally,
the lack of debug provided by the dispatch CLI tool made this very hard to
figure out the root problem.

Thank you,
Mike

**Comment by tsuwandy** [comment] 2019-05-20 19:47
@Stikemanley I can't see the [image: image.png], I think it's not linked?  

Where were the errors?  Could you copy and paste the errors instead?  I'm not sure what the issue is as you shouldn't need to import the json file yourself (cli will do it).
