### ISSUE TITLE
Virtual Assistant deployment error while executing the ‘luis add appazureaccount’ command

### ISSUE THREAD

**Issue by til10** [microsoft/botbuilder-tools#1227] opened 2019-07-26 23:40 UTC
#### What project is affected?

Virtual Assistant template

#### What language is this in?

C#

#### What happens?

There are errors generated during the deployment of a Virtual Assistant, which leads to a non-functional VA. 

#### What are the steps to reproduce this issue?

- Create a new project based on the latest VSIX template from master.
- Run `.\Deployment\Scripts\deploy.ps1 -parametersFile .\Deployment\Resources\parameters.template.json`

#### What were you expecting to happen?

An error-free deployment that results in a functional VA.

#### Can you share any logs, error output, etc.?

Console logs:
> Deploying Azure services (this could take a while)...
> Updating appsettings.json ...
> Deploying cognitive models ...
> Initializing dispatch model ...
> Parsing General LU file ...
> Deploying General LUIS app ...
> Setting LUIS subscription key ...
> ! Could not assign subscription key automatically. Review the log for more information.
> ! Log: C:\b\b19\b19\b19\Deployment\Scripts\..\deploy_cognitive_models_log.txt
> Please assign your subscription key manually in the LUIS portal.

From deploy_cognitive_models_log.txt: 
> The command line is too long.

_Note that the _armToken_ parameter to the ‘luis add appazureaccount’ command is close to 8000 characters long._

**Comment by sgellock** [comment] 2019-08-08 03:40
@stevengum can you do some work to pinpoint where this is failing?  It's largely been routed without much help.

**Comment by stevengum** [comment] 2019-08-08 18:20
Generating a token via `az account get-access-token` returns a token is ~1900 characters, which is well short of the 8000 characters noted in the original issue. 

I'll see if I can get a reproduction with the VSIX for the Virtual Assistant.

**Comment by til10** [comment] 2019-08-16 17:20
Group memberships seem to influence token size the most. The size can be under 2000 characters with relatively few entries in the 'groups' section.

**Comment by darrenj** [comment] 2019-08-20 11:46
@til10 can you confirm the size of the token that you get when running `az account get-access-token`

For reference this is the command being used in the deployment script.

```
luis add appazureaccount `
	--appId $luisApp.id `
	--authoringKey $luisAuthoringKey `
	--region $luisAuthoringRegion `
	--accountName $luisAccountName `
	--azureSubscriptionId $azAccount.id `
	--resourceGroup $resourceGroup `
	--armToken "$($azAccessToken.accessToken)"
```

**Comment by stevengum** [comment] 2019-08-20 16:29
@til10 for reproduction purposes, how many groups are you a member/owner of in AAD?

**Comment by til10** [comment] 2019-08-20 22:39
@darrenj too large and @stevengum too many, so it seems...

`$(Invoke-Expression "az account get-access-token --output json" | ConvertFrom-Json).accessToken.length`

A relatively unladen service principal could potentially be used as a workaround?

**Comment by darrenj** [comment] 2019-08-21 13:56
Are there any other options for how we can provide the armToken to the luis CLI? Not sure it will make any difference but piping perhaps? Perhaps something the az cli team have seen and could offer some approaches?

**Comment by stevengum** [comment] 2019-08-21 15:54
I'll create a dummy token over 8000 char in length and see where in the code it throws a fit. To me it's not 100% clear, but it seems plausible that the error is being thrown in the generated code, the service, or from PowerShell.

**Comment by stevengum** [comment] 2019-08-23 18:31
After testing the command in VS Code, it's not a problem in the code base. The dummy token wasn't rejected because of its length, just because it was an invalid token.

This requirement on length is actually due to Windows: https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation

After searching for workarounds, it seems that using a relatively unladen service principal _might_ be a valid workaround. Alternatively there could be an enhancement to the CLI tool in the future that makes it possible to pass in a file that contains the ARM token instead of passing it in directly via the cmd.

@emiliomunoz FYI

**Comment by stevengum** [comment] 2019-09-19 23:39
Spoke with @jspruance in person to brief him on this issue; he's going to work on it for the 4.6 timeframe.

Thanks @jspruance!

**Comment by jspruance** [comment] 2019-10-04 23:15
Update: PR #1313 added for this issue. Working on adding some tests now.

**Comment by jspruance** [comment] 2019-10-21 19:11
Requested review from Steven Gum
https://github.com/microsoft/botbuilder-tools/pull/1313

**Comment by sgellock** [comment] 2019-10-23 17:20
PR #1313 was merged.

**Closed by sgellock** 2019-10-23 17:20 UTC
Labels: 4.6, Bot Services, customer-replied-to, customer-reported, luis-cli
