### ISSUE TITLE
Luisgen not adding new KB to DispatchLuis.ts on mac

### ISSUE THREAD

**Issue by mbwatty** [microsoft/botbuilder-tools#1266] opened 2019-08-15 07:27 UTC
#### What project is affected?
luisgen

#### What language is this in?
Typescript

#### What happens?
When trying to add a new knowledgebase to the dispatch model luisgen generates an empty DispatchLuis.ts file. 

#### What are the steps to reproduce this issue?
I initially had issues getting luisgen working on my mac but this solved it [2075](https://github.com/microsoft/botframework-solutions/issues/2075). 
After adding the new KB to dispatch and refreshing dispatch successfully (I think) I then tried to update luisgen with 
`luisgen "deployment/resources/Dispatch/TheSafetyBoten_Dispatch.dispatch" -ts "DispatchLuis" -o "src/services"`

#### What were you expecting to happen?
An updated DispatchLuis.ts file with the new KB intent.

#### Can you share any logs, error output, etc.?
```
Generating file src/services/DispatchLuis.ts that contains interface DispatchLuis.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at LUISGen.Typescript.Intents(Object app, Writer w) in D:\a\1\s\packages\LUISGen\src\Typescript.cs:line 31
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at LUISGen.Typescript.Generate(String description, Object app, String className, String outPath) in D:\a\1\s\packages\LUISGen\src\Typescript.cs:line 205
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid5[T0,T1,T2,T3,T4](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at LUISGen.Program.Main(String[] args) in D:\a\1\s\packages\LUISGen\src\Program.cs:line 179
Abort trap: 6
```

**Comment by Batta32** [comment] 2019-08-20 19:12
Hi @mbwatty!

This looks like a LUISGen's issue, however, reviewing the log that you attached we found the following:

- The error `Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.` is raised in [Typescript.cs:line  31](https://github.com/microsoft/botbuilder-tools/blob/master/packages/LUISGen/src/Typescript.cs#L31) which iterates by each intent of your app (your dispatch) and the result of that object is **null**.

![image](https://user-images.githubusercontent.com/11904023/63376868-2d432880-c365-11e9-877e-48c0e208d65c.png)

- Can you check that the `dispatch refresh` was executed and if you have a model deployed and trained correctly? 
- Have you tried using `-cs` instead of `-ts`?

**Comment by hcyang** [comment] 2019-09-07 23:36
Hi @mbwatty, we are going to close this issue. If necessary, please reopen it if the issue is still note addressed. Thanks.

**Closed by hcyang** 2019-09-07 23:36 UTC
Labels: Bot Services, customer-replied-to, customer-reported
