### ISSUE TITLE
"dispatch create" output does not set region

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#407] opened 2018-09-04 16:22 UTC
**Describe the bug**
When piping the output of dispatch create into msbot connect dispatch, the region field is blank.

**To Reproduce**
`
dispatch create --name $FileName --bot $BotFilePath --luisAuthoringRegion $luisLocation --luisAuthoringKey $luisAuthoringKey --subscriptionKey $SubscriptionKey --dataFolder $OutputPath | msbot connect dispatch --stdin --bot $BotFilePath
`

.bot output:
`
    {
      "type": "dispatch",
      "id": "***",
      "name": "**************",
      "appId": "**********",
      "authoringKey": "**********",
      "serviceIds": [
        "***",
        "***"
      ],
      "subscriptionKey": "**************",
      "version": "Dispatch",
      "region": ""
    }
`

**Expected behavior**
Expect region property to be populated.

**Context**
Dispatch version: 1.0.8-1

**Comment by tsuwandy** [comment] 2018-09-04 16:29
Region is a new property recently added to LuisService in bot config.  I'm currently updating Dispatch code to use the latest bot configuration -  this should be fixed when that work is done.  Thanks!

**Comment by vishwacsena** [comment] 2018-09-04 17:19
dupe of #365

**Closed by vishwacsena** 2018-09-04 17:19 UTC
Labels: Approved, Next-Iteration, dispatch-cli

**Comment by tsuwandy** [comment] 2018-09-17 07:39
Merged to master, will be fixed when npm package is updated for Ignite
