### ISSUE TITLE
Dispatch create fails with Cannot find model expert in the specified application version

### ISSUE THREAD

**Issue by datarocker974** [microsoft/botbuilder-tools#1472] opened 2020-09-25 13:41 UTC
## Tool
Name: [Dispatch]
Version: 1.7.1
OS: Windows 10

## Describe the bug
I'm trying to generate a dispatch model from my .dispatch file. Just before, I added several LUIS apps and one QnA Maker knowledge base to the .dispatch file. 

All the previous steps went without any problems:
- Exporting services for dispatch...,
- Exporting the different LUIS applications
- Creating dispatch LUIS model json...
- Creating training data...
- Updating dispatch model...
- Training the different LUIS applications

The problem occurs when importing the dispatch model...
```
Creating dispatch LUIS model json...
Creating training data...
Updating dtnlsDisp model...
Training Communication...
Training SearchSomething...
Training WeatherForecast...
Training DtnlsLuis...
Importing dtnlsDisp model...

ERROR
Failed importing dtnlsDisp app - {
  "error": {
    "code": "BadArgument",
    "message": "Cannot find model expert in the specified application version."
  }
}
```

I can easily export the LUIS models manually in both formats (.LU and .JSON).
**Note**: some of my LUIS models have patterns with entities (2 or 3).

## To Reproduce

1. Include the desired models in the dispatch tool
2. Run dispatch create

## Screenshots
![Screenshot](https://user-images.githubusercontent.com/71882745/94273661-be67d400-ff55-11ea-9e50-01d96f16a170.jpg)

## Additional context
N/A

Does anyone have any idea what could be causing this type of error ?

[bug]

**Comment by ninggao** [comment] 2020-09-25 18:17
@tsuwandy Can you take a look at this please?

**Comment by tsuwandy** [comment] 2020-09-25 22:37
@datarocker974, is it possible for you to email .dispatch file and the json files in the dispatch folder (ie _L_<luis name>.json/_Q_<qna kb name>.json?  Feel free to remove the authoring/subscription keys from .dispatch file.    Please email to tien.suwandy@microsoft.com.  Thanks!

**Comment by datarocker974** [comment] 2020-09-27 10:33
Hi guys, thanks a lot for your help !!!
@tsuwandy, I just sent you an email with the .dispatch file and the json files in my dispatch folder. Let me know if you need anything else.

**Comment by tsuwandy** [comment] 2020-09-29 08:43
@datarocker974, the issue is with DtnlsLuis sub LUIS app.  There are a few complex entities used in pattern.  Dispatch transferred entities used in pattern.  However, with LUIS latest schema/feature, these entities could have child entities, which are not transferred to dispatch app.

I tried removing the entities with child entities and dispatch create is succesful..  See a few of these entities removed.  Current workaround is remove these entities from pattern OR remove the child entities from entities used in pattern.

![image](https://user-images.githubusercontent.com/10739108/94534220-fa6c9480-01f4-11eb-99d4-ce33497f4486.png)

Would it be possible to do this?

**Comment by datarocker974** [comment] 2020-09-30 12:52
Hi @tsuwandy,

Thanks a lot for your advice !
It's ok, I managed to generate my dispatch model by removing the patterns which contained complex entities.

However, I noticed that the patterns present in the None entity of the DtnlsLuis sub LUIS app were imported as the pattern of l_DtnlsLuis instead of None intent in the dispatch model. 

For now I can move the patterns manually from the LUIS web UI, but will my local .dispatch file sync and update when running the "refresh" command ?

**Comment by tsuwandy** [comment] 2020-09-30 15:23
@datarocker974, Thanks for the update.   As long as the changes are made to the sub LUIS app (not dispatch app), dispatch refresh should pick up the changes.   

The none pattern seems like a bug, people don’t use pattern for None.  I would remove it and instead set a confidence threshold for actual intents, ie don’t use it if confidence is less than 0.4 (try to find some number which will work for your scenario) or less.  

I’ll close this issue.  Let me know if you still have any issues.  Thank you!

**Closed by tsuwandy** 2020-09-30 15:23 UTC
Labels: Bot Services, customer-replied-to, customer-reported
