### ISSUE TITLE
[P0] MSBOT does not install from MyGet feed [Windows]

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#410] opened 2018-09-04 20:56 UTC
On a windows 10 machine - 

> npm uninstall -g msbot
> npm config set registry https://botbuilder.myget.org/F/botbuilder-tools-daily/npm/
> npm i -g msbot
npm ERR! path C:\Users\vkannan\AppData\Roaming\npm\node_modules\msbot\bin\msbot.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\Users\vkannan\AppData\Roaming\npm\node_modules\msbot\bin\msbot.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vkannan\AppData\Roaming\npm-cache\_logs\2018-09-04T20_54_35_709Z-debug.log

**Comment by enzocanoo** [comment] 2018-09-05 18:49
Fixed with #412. The cause of the problem was an issue with the publish script.

**Closed** 2018-09-07 18:06 UTC
Labels: Approved, Next-Iteration, msbot-cli
