### ISSUE TITLE
[Dispatch CLI] Include tool and version identifier in User-Agent header on all calls to LUIS APIs

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#743] opened 2018-11-08 00:00 UTC
Dispatch-CLI

Is your feature request related to a problem? Please describe.
Today, we do not have any view into LUIS traffic that are driven by botbuilder. LUIS service instruments all calls to the service and can report on User-Agent to identify the specific client.

Describe the solution you'd like
On all calls to LUIS service, include User-Agent header with the following value -
botbuilder/cli/dispatch/major.minor.patch.build

[enhancement]

**Comment by CoHealer** [comment] 2018-11-08 17:42
Duplicate of issue #742

**Comment by vishwacsena** [comment] 2018-11-08 17:51
We need two separate tickets one for the LUIS CLI and another for Dispatch CLI. that distinction was in the issue description but please feel free to add to the title if needed.

**Comment by CoHealer** [comment] 2018-11-08 18:17
My bad Vishwac, I didn't see that distinction in the description. I've removed the duplicate tag. Dispatch-CLI in the label and description seems fine to me!

**Comment by johnataylor** [comment] 2018-12-05 19:17
The HTTP call is actually made from a C# DLL and the source code to that isn't in this repo. So the user-agent needs to be added in that code. Assigning this to @tsuwandy

**Comment by tsuwandy** [comment] 2018-12-05 19:44
Dispatch code updated, to be merged in today.

**Closed by tsuwandy** 2018-12-05 19:44 UTC
Labels: 4.2, Approved, Dispatch-cli
