### ISSUE TITLE
dispatch create includes prompts when includePrompts is set to false

### ISSUE THREAD

**Issue by jrpavoncello** [microsoft/botbuilder-tools#1478] opened 2020-10-26 16:16 UTC
## Tool
Name: Dispatch
Version: botdispatch@1.7.1
OS: Windows 10 Pro, Version 10.0.17763 Build 17763

## Describe the bug
When we set the flag "includePrompts" to false when adding qna resources to a dispatch model, the LUIS dispatch model is generated with context-only prompts from multi-turn, QnA pairs as utterances.

Or am I misunderstanding what includePrompts actually does?

## To Reproduce
1. dispatch init -n dev-luis-prototype1-main --luisAuthoringKey ################################ --luisAuthoringRegion westus

2. dispatch add -type qna -id ########-####-####-####-############ --name FAQ -key ################################ --includePrompts false --includeMetadata false --includeAnswersForTraining false

This knowledge base contains the context-only prompts. I've included an example .json exported from the knowledgebase we are using to produce the issues. [faq.json.txt](https://github.com/microsoft/botbuilder-tools/files/5439924/faq.json.txt)

3. dispatch add -type qna -id ########-####-####-####-############ --name unsupported -key ################################ --includePrompts false --includeMetadata false --includeAnswersForTraining false

This can be any other knowledge base.

4. dispatch create --useAllTrainingData true -c en-us
5. Look at the utterances for the q_FAQ intent, they contain prompts.

## Expected behavior
I would expect that when I specify "--includePrompts false" that it does not include the context-only questions form multi-turn questions.

## Screenshots
From qnamaker.ai, a screenshot of one of the context-only questions that belongs to a multi-turn question. I verified this is the only question that is "No":

![image](https://user-images.githubusercontent.com/2867338/97197227-c5b41480-1783-11eb-84e2-128d6710a829.png)

From the generated dispatch LUIS model:

![image](https://user-images.githubusercontent.com/2867338/97197810-70c4ce00-1784-11eb-93f2-15ab24b12fe2.png)
![image](https://user-images.githubusercontent.com/2867338/97197603-3a874e80-1784-11eb-93e9-a2f7e2d3de44.png)

[bug]

**Comment by Zerryth** [comment] 2020-10-28 20:03
@jrpavoncello I can confirm that I got the same results as you, running:

* `dispatch init`
* `dispatch add -t qna -i 7b13xxxx-xxxx-xxxx-xxxx-xxxxxxxx511e -n Faq -k 94cxxxxxxxxxxxxxxxxxxxxxxxxxxa27 --includePrompts false`
* `dispatch create`

In QnA Maker portal, I have a model that includes multi-turn prompt:
![image](https://user-images.githubusercontent.com/35248895/97489890-612cbd00-191d-11eb-98d6-1c9bd4d35fbe.png)

![image](https://user-images.githubusercontent.com/35248895/97489921-70ac0600-191d-11eb-8268-f376f32b6715.png)

However even though the `dispatch add -t qna` command had `--includePrompts false`, the LUIS model still includes Context-Only questions are still showing up in the dispatch LUIS model created:
![image](https://user-images.githubusercontent.com/35248895/97490346-ef08a800-191d-11eb-8380-0c411434fac7.png)

____

Going to reach out to our team and verify if both of our expectations of the `--includePrompts` flag is incorrect and get back to you

**Comment by jrpavoncello** [comment] 2020-10-28 20:29
Thanks so much!

**Comment by Zerryth** [comment] 2020-10-28 21:00
Alright, so the engineer who specializes with this particular tool is out until next week, but she let me know she'll take a look at this to confirm one way or another when she's back!

Spoke to another engineer who said 3 flags are related (from [dispatch readme](https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch)):

Option | Description
-- | --
--includeAnswersForTraining | (optional for QnA only) Default to false. If set to true, QnA KB answers will be included in the training set
--includeMetadata | (optional for QnA only) Default to false. If set to true, QnA KB metadata will be included in the training set
--includePrompts | (optional for QnA only) Default to false. If set to true, QnA KB prompt questions will be included in the training set

> If your customer does not want answers in the final LUIS file, he/she should ensure --includeAnswersForTraining is set to false (which is the default).

However I tried `dispatch add -t qna -i 7b13xxxx-xxxx-xxxx-xxxx-xxxxxxxx511e -n Faq -k 94cxxxxxxxxxxxxxxxxxxxxxxxx2a27 --includeAnswersForTraining false --includePrompts false` and I still see questions and answers labelled as CONTEXT-ONLY in QnA Maker portal showing up in the LUIS dispatch model, which to me also seems to indicate more unexpected behavior...
___

Anyways, wanted to apprise you of what I know so far, and thank for your patience 😄.

**Comment by jrpavoncello** [comment] 2020-10-29 00:05
Well, I'm glad I'm not crazy at least lol. Thank you for the followups. I can also confirm I have set those flags explicitly to false and it will produce the unexpected behavior.

Also just a side note, since the documentation says the default for --includePrompts is **false**  -  I'm seeing in Dispatch.dll, QnAMakerSource.CreateFromNamedArgs, includePrompts defaults to **true**. I see that the default value of includePrompts from the constructor of QnAMakerSource is **false**, but without having dug too deeply into it, I believe CreateFromNamedArgs is called when you add a QnA type source to the dispatch model, which would overwrite the constructor's default.

**Comment by Zerryth** [comment] 2020-10-29 01:03
@jrpavoncello Alright, got more insight as to what's happening with the flags.

Reference the example multi-turn conversation that I have in my QnA model in [my earlier comment](https://github.com/microsoft/botbuilder-tools/issues/1478#issuecomment-718177125) for context.

So in my model I have the first question of:
* How do I set my favorite color? (question)
   * green (prompt)
   * red (prompt)

And if you select "green":
* green (question)
   * sea foam (prompt)
   * shamrock (prompt)

And then it you can select an answer further from there.

Anyways, when I put the flags `includePrompts` and `includeAnswersForTraining` as false, what we're telling Dispatch to do is to "include `question` fields in the training model that Dispatch creates." 

Now yes my "green" *does* show up as a prompt in the initial question, however it also is set up as a question. Because it shows up as a question, Dispatch picks it up as training data.

#### QnA Maker API Request/Response for Multi-Turn Scenario
<details>
<summary>First question</summary>

Request
```json
{
	"question": "favorite color",
	"top": 10,
	"context": { 
		"previousQnaId": 17
	}
}
```

Response
```json
{
    "answers": [
        {
            "questions": [
                "How do I set my favorite color?",
                "favorite color"
            ],
            "answer": "Choose color group",
            "score": 100.0,
            "id": 11,
            "source": "Editorial",
            "metadata": [],
            "context": {
                "isContextOnly": false,
                "prompts": [
                    {
                        "displayOrder": 0,
                        "qnaId": 12,
                        "displayText": "green"
                    },
                    {
                        "displayOrder": 0,
                        "qnaId": 14,
                        "displayText": "red"
                    }
                ]
            }
        }
    ],
    "activeLearningEnabled": true
}
```

</details>


<details>
<summary>Responding to "favorite color" question by selecting "green"</summary>

Request
```json
{
  "question": "green",
  "top": 10,
  "qnaId": 12,
  "context": {
    "previousQnAId": 11,
    "previousUserQuery": "favorite color"
  }
}
```

Response
```json
{
    "answers": [
        {
            "questions": [
                "green"
            ],
            "answer": "Select a type of green",
            "score": 100.0,
            "id": 12,
            "source": "Editorial",
            "metadata": [],
            "context": {
                "isContextOnly": true,
                "prompts": [
                    {
                        "displayOrder": 0,
                        "qnaId": 13,
                        "displayText": "sea foam"
                    },
                    {
                        "displayOrder": 0,
                        "qnaId": 15,
                        "displayText": "shamrock"
                    }
                ]
            }
        }
    ],
    "activeLearningEnabled": true
}
```
</details>

___

If you were to ask my opinion, it'd be great if there were a flag that specifically target all things in QnA Maker that's labeled as "CONTEXT-ONLY" that you see in the portal with Dispatch, however unfortunately there isn't anything of the sort. 

I asked an engineer on the team as well, and we currently won't be adding this feature to Dispatch either, because our efforts are focused on fine-tuning Orchestrator, which will be the "new", shiny and better Dispatch tool, which is currently in preview:
https://www.npmjs.com/package/@microsoft/bf-orchestrator-cli

Sorry for the unexpected behavior. It seems like the only workaround is to manually edit the LUIS app and delete the extra utterances.

**Closed by Zerryth** 2020-10-29 01:03 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by Zerryth** [comment] 2020-10-29 01:04
To clarify, Dispatch was a tool that was created before the newer QnA Maker feature of multi-turn questions came about--just FYI, as to how this discrepancy occurred in the first place

**Comment by jrpavoncello** [comment] 2020-10-29 02:25
@Zerryth That makes sense, thanks for the extra clarification. Does the orchestrator cli current have the capabilities to exclude context-only questions?

**Comment by jrpavoncello** [comment] 2020-10-29 02:29
If so, we'll switch over to it even if it's in preview. But we'll do the workaround if not :)

**Comment by Zerryth** [comment] 2020-10-29 16:46
I'm afraid Orchestrator doesn't have such flag currently right now either 😞
