### ISSUE TITLE
LUISGen creates incorrect package names

### ISSUE THREAD

**Issue by mekinney** [Microsoft/botbuilder-tools#1060] opened 2019-04-10 22:29 UTC
## Tool
Name: LuisGen
Version: 2.0.2.0

## Describe the bug
Clearly, I'm doing something wrong because this is too obvious not to have been fixed.

I'm building the VirtualAssistant and LUISGen creates the incorrect CS files for Intents and Entities.

Correct Code included with VirtualAssistant project:
```csharp
// <auto-generated>
// Code generated by LUISGen
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public class CalendarLU: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            AcceptEventEntry, 
            ChangeCalendarEntry, 
            CheckAvailability, 
            ConnectToMeeting, 
            ContactMeetingAttendees, 
            CreateCalendarEntry, 
            DeleteCalendarEntry, 
            FindCalendarDetail, 
            FindCalendarEntry, 
            FindCalendarWhen, 
            FindCalendarWhere, 
            FindCalendarWho, 
            FindDuration, 
            FindMeetingRoom, 
            GoBack, 
            None, 
            ShowNextCalendar, 
            ShowPreviousCalendar, 
            TimeRemaining
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Subject;
            public string[] FromDate;
            public string[] FromTime;
            public string[] ToTime;
            public string[] MeetingRoom;
            public string[] Location;
            public string[] MoveEarlierTimeSpan;
            public string[] MoveLaterTimeSpan;
            public string[] ToDate;
            public string[] SlotAttribute;
            public string[] OrderReference;
            public string[] PositionReference;
            public string[] Message;
            public string[] Duration;
            public string[] DestinationCalendar;

            // Built-in entities
            public DateTimeSpec[] datetime;
            public double[] number;
            public double[] ordinal;
            public string[] personName;

            // Lists
            public string[][] RelationshipName;

            // Instance
            public class _Instance
            {
                public InstanceData[] Subject;
                public InstanceData[] FromDate;
                public InstanceData[] FromTime;
                public InstanceData[] ToTime;
                public InstanceData[] MeetingRoom;
                public InstanceData[] Location;
                public InstanceData[] MoveEarlierTimeSpan;
                public InstanceData[] MoveLaterTimeSpan;
                public InstanceData[] ToDate;
                public InstanceData[] SlotAttribute;
                public InstanceData[] OrderReference;
                public InstanceData[] PositionReference;
                public InstanceData[] Message;
                public InstanceData[] Duration;
                public InstanceData[] DestinationCalendar;
                public InstanceData[] datetime;
                public InstanceData[] number;
                public InstanceData[] ordinal;
                public InstanceData[] personName;
                public InstanceData[] RelationshipName;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<CalendarLU>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
```

Code generated by LuisGen 2.0.2.0 has a number of errors:
Using statements are missing.
Namespaces are incorrect (Microsoft.Bot.Builder.Core.Extensions.IRecognizerConvert and Microsoft.Bot.Builder.Ai.LUIS.IntentData).

```csharp
// <auto-generated>
// Code generated by LUISGen C:\Code\AI\solutions\Virtual-Assistant\src\csharp\assistant\DeploymentScripts\..\LocaleConfigurations\..\DeploymentScripts\en\calendar.luis -cs Luis.CalendarLU -o C:\Code\AI\solutions\Virtual-Assistant\src\csharp\assistant\DeploymentScripts\..\LocaleConfigurations\..\..\skills\calendarskill\calendarskill\CognitiveModels\LUIS\en\calendar.lu\..\..\..\..\Dialogs\Shared\Resources
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
namespace Luis
{
    public class CalendarLU: Microsoft.Bot.Builder.Core.Extensions.IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            AcceptEventEntry, 
            ChangeCalendarEntry, 
            CheckAvailability, 
            ConnectToMeeting, 
            ContactMeetingAttendees, 
            CreateCalendarEntry, 
            DeleteCalendarEntry, 
            FindCalendarDetail, 
            FindCalendarEntry, 
            FindCalendarWhen, 
            FindCalendarWhere, 
            FindCalendarWho, 
            FindDuration, 
            FindMeetingRoom, 
            GoBack, 
            None, 
            ShowNextCalendar, 
            ShowPreviousCalendar, 
            TimeRemaining
        };
        public Dictionary<Intent, Microsoft.Bot.Builder.Ai.LUIS.IntentData> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Subject;
            public string[] FromDate;
            public string[] FromTime;
            public string[] ToTime;
            public string[] MeetingRoom;
            public string[] Location;
            public string[] MoveEarlierTimeSpan;
            public string[] MoveLaterTimeSpan;
            public string[] ToDate;
            public string[] SlotAttribute;
            public string[] OrderReference;
            public string[] PositionReference;
            public string[] Message;
            public string[] Duration;
            public string[] DestinationCalendar;

            // Built-in entities
            public Microsoft.Bot.Builder.Ai.LUIS.DateTimeSpec[] datetime;
            public double[] number;
            public double[] ordinal;
            public string[] personName;

            // Lists
            public string[][] RelationshipName;

            // Instance
            public class _Instance
            {
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] Subject;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] FromDate;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] FromTime;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] ToTime;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] MeetingRoom;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] Location;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] MoveEarlierTimeSpan;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] MoveLaterTimeSpan;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] ToDate;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] SlotAttribute;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] OrderReference;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] PositionReference;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] Message;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] Duration;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] DestinationCalendar;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] datetime;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] number;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] ordinal;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] personName;
                public Microsoft.Bot.Builder.Ai.LUIS.InstanceData[] RelationshipName;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<CalendarLU>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score;
                }
            }
            return (maxIntent, max);
        }
    }
}

```

[bug]

**Comment by AmirGeorge** [comment] 2019-04-18 13:34
It doesn't seem like the output from LuisGen has recently changed. The using statements are still there. @cahann please assign someone from the VA team to take a look.

**Comment by cahann** [comment] 2019-04-18 14:00
@darrenj who is the right person in your team to look into this issue?

**Comment by darrenj** [comment] 2019-04-18 14:11
Don't think it's an issue on our side?  I've just re-run luisgen for the attached Calendar.json file and it matches the original example given, I can't repro the 2nd example?

This is on version 2.0.2.0

```
// <auto-generated>
// Code generated by LUISGen calendar.json -cs Luis.CalendarLU -o 
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Luis
{
    public class CalendarLU: IRecognizerConvert
    {
        public string Text;
        public string AlteredText;
        public enum Intent {
            AcceptEventEntry, 
            ChangeCalendarEntry, 
            CheckAvailability, 
            ConnectToMeeting, 
            ContactMeetingAttendees, 
            CreateCalendarEntry, 
            DeleteCalendarEntry, 
            FindCalendarDetail, 
            FindCalendarEntry, 
            FindCalendarWhen, 
            FindCalendarWhere, 
            FindCalendarWho, 
            FindDuration, 
            FindMeetingRoom, 
            GoBack, 
            None, 
            ShowNextCalendar, 
            ShowPreviousCalendar, 
            TimeRemaining
        };
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Subject;
            public string[] FromDate;
            public string[] FromTime;
            public string[] ToTime;
            public string[] MeetingRoom;
            public string[] Location;
            public string[] MoveEarlierTimeSpan;
            public string[] MoveLaterTimeSpan;
            public string[] ToDate;
            public string[] SlotAttribute;
            public string[] OrderReference;
            public string[] PositionReference;
            public string[] Message;
            public string[] Duration;
            public string[] DestinationCalendar;

            // Built-in entities
            public DateTimeSpec[] datetime;
            public double[] number;
            public double[] ordinal;
            public string[] personName;

            // Lists
            public string[][] RelationshipName;

            // Instance
            public class _Instance
            {
                public InstanceData[] Subject;
                public InstanceData[] FromDate;
                public InstanceData[] FromTime;
                public InstanceData[] ToTime;
                public InstanceData[] MeetingRoom;
                public InstanceData[] Location;
                public InstanceData[] MoveEarlierTimeSpan;
                public InstanceData[] MoveLaterTimeSpan;
                public InstanceData[] ToDate;
                public InstanceData[] SlotAttribute;
                public InstanceData[] OrderReference;
                public InstanceData[] PositionReference;
                public InstanceData[] Message;
                public InstanceData[] Duration;
                public InstanceData[] DestinationCalendar;
                public InstanceData[] datetime;
                public InstanceData[] number;
                public InstanceData[] ordinal;
                public InstanceData[] personName;
                public InstanceData[] RelationshipName;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<CalendarLU>(JsonConvert.SerializeObject(result));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
```



[calendar.zip](https://github.com/Microsoft/botbuilder-tools/files/3094738/calendar.zip)

**Comment by mekinney** [comment] 2019-04-18 20:58
On vacation, so slow response and can’t retest. Daily build worked for me. Seems to be a release issue, if that helps.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AmirGeorge** [comment] 2019-04-22 12:56
Closing as we can't reproduce the issue. @mekinney feel free to reopen if you have repro steps to follow. Thanks!

**Closed by AmirGeorge** 2019-04-22 12:56 UTC
Labels: 4.4, Bug, P1, luisgen
